.tmuxinator.yml

We changed the structure of the folders that contain the validator info (`identity.json`, `validators.json`, and sometimes `state.bin`), which broke the tmux script we use for testing. This change fixes the tmux script to assume there are 4 folders (named `0`, `1`, `2`, and `3`) each containing a set of validator info.

Fix tmux script

---

protocol/operation.re

Operations could not be deserialized because the way hashes were calculated when serializing and deserializing was not consistent.  This should fix that issue. Ideally, the code would not be duplicated in the first place, I'm interested in comments on how that might be possible.

Make hashing and unhashing consistent

---

node/building_blocks.re

The previous block height error just said "new block has a lower block height". This is useful, but it can be handy to know the expected and actual heights (For instance, that can be useful to know it's an off-by-one error or if they're way off). This MR changes the assertion message to include the height of the new block and the expected height, in cases where the block height is not greater than or equal to the expected height. 
This is not a totally free change, since there's probably a tiny cost to the performance caused by creating the string, but I think it should probably be totally undetectable.

Make block-height error more informative

---

bin/dune
bin/http_server.re
bin/sidecli.re
esy.lock/index.json
esy.lock/opam/faraday-lwt-unix.0.7.3/opam
esy.lock/opam/faraday-lwt.0.7.3/opam
esy.lock/opam/faraday.0.7.3/opam
esy.lock/overrides/opam__s__zarith_opam__c__1.12_opam_override/package.json
node/flows.re
node/networking.re
package.json
protocol/address.re
protocol/address.rei
protocol/operation.re
protocol/operation.rei
protocol/wallet.re
protocol/wallet.rei
tests/test_protocol.re

This PR has two components:
1) It extends the validators to support gossiping about new operations to include on the chain. It uses a super-simple flood system, where any validator can receive an operation and, if it's new to them, will send it to all the other validator they're connected to (who will then do the same thing etc). Someone could easily DOS the network by sending a bunch of operations really fast, there's no protection against that, and I'm not sure how other blockchains deal with this issue. An easy fix would be to require PoW on each transaction, but that has tradeoffs. 
2) It adds a simple CLI, implemented with Cmdliner, for creating wallets and submitting transactions to the pool of operations.
What still needs to be done, possibly in a future MR:
1) Double check to make …

Add basic CLI for creating transactions

---

tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Most of the problem should be described at #30 but this specifically is being added so we can transmit proofs of withdraw to Tezos for tickets communication.
This duplicates Tezos encoding logic to sidechain to avoid having a hard dependency on `tezos-crypto` the logic can be tracked from:
https://gitlab.com/tezos/tezos/-/blob/master/src/lib_crypto/ed25519.ml
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/script_ir_translator.ml#L514
```shell
echo "let pack = (data: key_hash) => Bytes.pack(data)" > test.religo
ligo evaluate-call test.religo pack "(\"tz1LzCSmZHG3jDvqxA8SG8WqbrJ9wz5eUCLC\": key_hash)"
```
- #34

support key_hash on PACK

---

tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

This is required so that we can transmit proofs of withdraw to Tezos for tickets communication.
This duplicates Tezos logic to sidechain to avoid having a hard dependency on tezos-crypto the logic can be tracked from:
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/contract_repr.ml
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/script_ir_translator.ml#L466
```shell
echo "let pack = (data: address) => Bytes.pack(data)" > test.religo
ligo evaluate-call test.religo pack "(\"tz1LzCSmZHG3jDvqxA8SG8WqbrJ9wz5eUCLC\": address)"
```
- #34

support address on tezos_interop

---

tests/test_tezos_interop.re
tezos_interop/base58.ml
tezos_interop/base58.mli
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Currently only smart contracts can hold tickets, so a deposit of tickets from tezos can only happen from an KT1 address, withdraws can also happen to a smartcontract, but sidechains currently doesn't support KT1
This duplicates Tezos logic to sidechain to avoid having a hard dependency on tezos-crypto the logic can be tracked from:
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/contract_repr.ml
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/script_ir_translator.ml#L466
```ocaml
echo "let pack = (data: address) => Bytes.pack(data)" > test.religo
ligo evaluate-call test.religo pack "(\"KT1Dbav7SYrJFpd3bT7sVFDS9MPp4F5gABTc\": address)"
```
- #34

support contract_hash on tezos_interop

---

bin/sidecli.re

Before
```
ARGUMENTS
MSG (required)
The message to print.
MSG (required)
The message to print.
MSG (required)
The message to print.
```
Now,
```
SYNOPSIS
sidecli create-transaction [OPTION]... sender receiver amount
ARGUMENTS
amount (required)
The amount to be transacted.
receiver (required)
The receiving address.
sender (required)
The sending address, or a path to a wallet. If a bare sending
address is provided, the corresponding wallet is assumed to be in
the working directory.
```

CLI: Fix doc strings for create-transaction

---

bin/sidecli.re
node/networking.re
node/state.re
node/state.rei
protocol/block.re
protocol/block.rei
protocol/operation.re
protocol/operation.rei
protocol/protocol.re
tests/test_protocol.re

This code was made in a couple of hours and was particularly brittle, and having two kinds of operations one checked and one not checked.
The goal here is to simplify it and enforce the invariant that all side operations **must be signed by the source** of the money

ensure that side chain operations are checked

---

helpers/BLAKE2B.re
helpers/helpers.re
helpers/incremental_patricia.re
helpers/incremental_patricia.rei
tests/dune
tests/test_incremental_patricia.re

To validate data on Tezos main chain during withdraws the user needs a way to provide a proof that he did burn the money on the sidechain.
We use a binary radix tree, where the key is always an incremental int, with this every money burnt will receive an id back that can be used to construct the proof.
- #34

add incremental patricia tree

---

tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

We need to be able to receive and store tickets(ticketer and data) in the sidechain coming from Tezos for deposit and withdraw.
Add a proper support for tickets in Tezos_interop, this duplicates Tezos logic to sidechain to avoid having a hard dependency on tezos-crypto the logic can be tracked from:
https://gitlab.com/tezos/tezos/-/blob/master/src/proto_alpha/lib_protocol/script_ir_translator.ml#L5850
- #34

support ticket on tezos_interop

---

protocol/wallet.re

An wallet address should be `H(pubkey)` but currently it is `H(JSON(pubkey))` this makes that the hashed addresses are invalid on Tezos.

fix wallet address hashing

---

protocol/operation.re
protocol/operation.rei
protocol/protocol.re
tests/test_protocol.re

Currently main chain operations have no identifier shared with tezos, so we cannot ensure that an operation already happened.
It is a temporary fix, it adds the tezos_hash to allow main chain operations to be properly indexed.

add tezos_hash to all main chain operations

---

LICENSE
package.json

We're lacking a license on the project, this means that while actually we're open source no one is allowed to use this code without our permission. But this project should be open source to allow others to use it freely.
As discussed with @Galfour in private everything at marigold is by default MIT unless explicitly discussed otherwise, so I'm just adding it here.
- closes #66

add MIT LICENSE

---

bin/dune
bin/files.re
bin/files.rei
bin/http_server.re
bin/sidecli.re

We've been duplicating logic for a while to handle files, namely `identity.json` and `validators.json`, this is getting quite messy especially when adding new files.
I made a library for file formats which currently sits as part of `bin`, this is not ideal but it solves the duplicated code problem without too many changes on the project structure.

make a library for files

---

README.md

**Problem**
Guidelines section is missing the preferred practice of having the problem description in the PR
**Solution**
Adds a section explaining the practise of having problem desciptions in the PR
** Depends on **
N/A

Readme: Add a note about PR descriptions

---

bin/files.re
bin/files.rei
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

To solve #61 we need to have some information about how to talk to Tezos, which rpc, consensus contract, validators and how many confirmations needed.
This PR adds a file where the required data can be parametrized externally.
- #61

add tezos_interop context files

---

bin/sidecli.re

Currently, the sidecli `man` information is duplicated in many places. 
We should have one man page "template", which is really just a list of man page items, and customize it as needed by prepending more information to the list. Since every man page is exactly the same right now, it's easy to move the repeated `man` definition to the top.
We should probably write more detailed man page information for each option at some point. I've created #80 to track that.

Don't repeat man information all over the place in sidecli

---

.tmuxinator.yml

Use pre_window field in the config to reliably set up the environment
in which cur__* variables are always present in all tmux panes.

Uses esy shell in .tmuxinator config

---

tezos_interop/consensus.mligo

Currently hashes are treated as sequence of bytes, but there is also some other things that are sequences of bytes like the result of `Bytes.pack`, it would be cool if we ensured that a hash is not just any sequence of bytes.
Sadly Ligo doesn't have nominal typing so for now I'm just adding an alias to makes it clear for us while reading the consensus contract.

add types for hashes in consensus contract

---

tests/test_tezos_interop.re
tezos_interop/consensus.mligo
tezos_interop/tezos_interop.re

To do withdraws from sidechain to Tezos we need to somehow provide proofs that the ticket was burned on the sidechain.
The goal here is to add a hash on every root_hash update for `handles_hash` which is the root hash 
of a patricia tree from an `id -> data`, this will allow a user to construct a proof when burning tickets.
Note that this is currently not implemented as the sidechain is committing always the same handles_hash and the goal of this PR is only to introduce it in the contract.
- #34

add handles hash to root hash

---

bin/sidecli.re
helpers/helpers.re
protocol/ledger.re
protocol/ledger.rei
protocol/operation.re
protocol/operation.rei
protocol/protocol.re
protocol/ticket.re
protocol/ticket.rei
tests/test_ledger.re
tests/test_protocol.re

Users should be able to operate on tickets.
This is solved through adding tickets to the ledger and to Transaction operation, because of this essentially the key for a ledger is a tuple between the `ticket` and wallet `address`.
- #34

add tickets to operations

---

tezos_interop/consensus.mligo

To achieve #34 we need a way to move money outside of the sidechain and have a proof to it so that Tezos can verify it.
As #85 we have the handles_hash here we add them for a set of handle_hash and when the user tries to withdraw it we verify the proof by assuming the hash represents a patricia tree where the key is always an incremental int.
After doing a withdraw the handle is added to a set of handles_id so that it cannot be used again.
- #34

add withdraw consensus contract

---

bin/http_server.re
node/state.re
node/state.rei

Currently the node cannot access the Tezos context which makes so that future PRs that require communication to Tezos currently don't work.
Add the context to the node state so that it can communicate to Tezos.
- #61

add interop context to node state

---

bin/http_server.re
bin/sidecli.re
node/flows.re
node/networking.re

**Problem**
To prevent replay attacks, `create-transaction` command must stamp the transaction requests to the node with the block level at which the transaction is expected to be baked.
**Solution**
This PR adds a `/block-level` endpoint to query the current block level and use it while signing the transaction operation.

Set block level in create-transaction command

---

README.md
bin/sidecli.re

See #73. Some files are needed to set up a node, a convenient command should be available to generate all of them. 
This adds a `setup-node` command to sidecli that takes the information needed to set up a node, and a folder, and creates the appropriate files inside that folder.

Add a sidecli subcommand to setup the node

---

tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

To keep the PR dependency graph simple, this one depends on
#88 adds on the Tezos contract a `handle_structure` which when combined with the `handles_hash` allow us to communicate proofs about the sidechain to Tezos, but currently there is no way to hash `handle_structure` on the sidechain.
This implements `hash_withdraw_handle` which creates a hash compatible with #88 `handle_structure`.
- #34
- #88

add hash_withdraw_handle on tezos interop

---

bin/files.re
protocol/ledger.re
protocol/ticket.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

This dependency is just to keep the PR graph simple.
In a couple different places we're duplicating code because currently Tezos_interop only exposes primitives, while this is desirable the cost of it right know is too high.
This is the first step to solve that by adding `to_yojson` and `of_yojson` on `Tezos_interop.Address`

add yojson on tezos interop address

---

protocol/operation.re
protocol/operation.rei
protocol/protocol.re

As part of the progress of #34 we removed the deposit operation so that it could be redesigned without major problems, but to finish it we need to add deposit back.
This PR adds a deposit operation which should(in the future) be detected when someone calls the deposit entrypoint on Tezos as per #83 
- #34 
- #83

add deposit operation

---

protocol/operation.re
protocol/operation.rei
protocol/protocol.re

To keep the dependency graph simple
As part of the progress of #34 we removed the withdraw operation so that it could be redesigned without major problems, but to finish it we need to add withdraw back.
This PR adds a withdraw operation which permits the user to burn the money on the sidechain and get a proof of it(in a future PR) to use it on the withdraw entrypoint on Tezos as per #88
- #34 
- #88

add withdraw operation

---

esy.lock/index.json
esy.lock/opam/digestif.1.0.0/opam
package.json
tezos_interop/run_entrypoint.js

To achieve #61 we should be able to run tezos contracts directly from the node, this currently is not possible.
Instead of reimplementing the logic to talk to a Tezos RPC and handle things like waiting for confirmations, this PR proposes that we use taquito by making node CLIs that can be in the future called by the node itself.
Essentially an API to talk to Ligo contracts provided by the sidechain.
I've used JSDoc to at least document the interface as IIRC typescript doesn't work well with esy sadly, also because this avoids a build step for now.
- #61

make cli to run tezos contracts with taquito

---

tezos_interop/dune
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

To achieve #61 we need to be able to commit the state hash from inside of the node.
This is a movement in this direction, it integrates on the CLI provided by #98 and exposes `commit_state_hash` which allows the node to call and submit the operation to Tezos.
- #61

add commit_state_hash to Tezos_interop

---

.github/workflows/test.yml
bin/sidecli.re

On a previous PR a duplicated block was introduced and this was not detected by the CI as we're always running build in production mode.
On this PR we also call `dune build @check` on the CI so that all the possible warnings are detected during future PRs and also fix the example.

ci: run dune build @check

---

bin/http_server.re
node/networking.re
protocol/block.re
protocol/block.rei
tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Currently the `handles_hash` is hardcoded not carrying the ledger proofs. So not being useful for withdraws.
Here we route the data from the ledger to a block, where it will be signed and eventually commited to the main chain where it can be then inspected and used for withdraws.
- #34 
- Same as #103

add handles hash to block

---

node/state.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

We need to commit the state hash to Tezos periodically so that it can be used for things like withdraws.
Here we just try to commit the state hash every new state hash, but with a delay of 120 seconds if you're not the author of the block, that way we avoid a bunch of validators trying to commit at the same time without a good reason.
This is not a good decision but it's a temporary fix in the direction of #61 
- #34 
- #61

try to commit state hash every new snapshot

---

node/state.re
protocol/signature.re
protocol/signature.rei

On #100 we added a function to commit the state hash automatically from the node and on #105 it was integrated, because this function was not properly tested it contained a bug on the signatures where the signature was actually a b58(b58(sign)) instead of b58(sign).
This PR fixes it and also move this abstraction to the Signature module, so that in the future it is properly tested.
- #34 
- #61

fix signatures on commit state hash

---

node/flows.re

Currently when an async global exceptions happens we only have `global exceptions` as an error message, which doesn't tell us anything about the error.
Properly print the error message to stderr and try to print the backtrace.

log global async exceptions

---

tezos_interop/run_entrypoint.js

`run_entrypoint` has a bug where it will submit the argument array as a single element an array, instead of spreading the arguments. 
- #34 
- #61

fix run_entrypoint

---

bin/sidecli.re

`produce-block` should be used to unstale a side chain by producing a block then sharing the hash and manually signing the block with `sign-block` but currently that's not possible as it doesn't return the hash .
This makes so that produce-block will print to the stdout something like `block.hash: HASH` which can be used together with `awk` to automate and replace `inject-genesis` but also to unstale the chain in a proper way.

print block hash on produce-block

---

.github/workflows/test.yml
.gitignore
esy.lock/index.json
esy.lock/opam/ppx_blob.0.7.2/opam
package.json
tezos_interop/dune
tezos_interop/tezos_interop.re
tezos_interop/webpack.config.js

Since #105 we use a JS script to commit the sidechain state hash to Tezos, this is a problem as to run this script we need not only `node` but also `esy` which all the dependencies installed locally.
This uses webpack to generate a standalone bundle and ppx_blob to inline the JS file in the binary, and during runtime the binary creates a temporary file with JS which will be used during the lifetime of the node.
With this you only need `node` available on the environment which is a much smaller requirement.
This requires you to update your esy to the latest nightly as esy had a problem related to JS packages inside of the `_esy`.

Inline JS scripts inside the node binary

---

esy.lock/index.json
esy.lock/opam/camomile.1.0.2/opam
esy.lock/opam/charInfo_width.1.1.0/opam
esy.lock/opam/lambda-term.3.1.0/opam
esy.lock/opam/lwt_log.1.1.1/opam
esy.lock/opam/lwt_react.1.1.4/opam
esy.lock/opam/mew.0.1.0/opam
esy.lock/opam/mew_vi.0.5.0/opam
esy.lock/opam/react.1.2.1/opam
esy.lock/opam/trie.1.0.0/opam
esy.lock/opam/utop.2.8.0/opam
esy.lock/opam/zed.3.1.0/opam
package.json
tools/dtop.re
tools/dune

`rtop` doesn't understand OCaml syntax emitted by `dune top` and needs a workaround - load the `cma` files first from the `use_output`, then activate the reason parsers in the REPL.
We could take this up in the Reason community and see if this can be fixed natively there.

Toplevel for REPL driven development

---

.tmuxinator.yml

If you make a change, `esy x <command>` rebuilds before executing the command, which messes up the timing (the nodes must start before inject-genesis runs, for example). 
This adds a line in the `.tmuxinator.yml` that builds the project before opening tmux, so everything is always built and the timings are right.

Tmuxinator: Build before starting tmux

---

tests/test_tezos_interop.re
tezos_interop/base58.ml
tezos_interop/base58.mli
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

To index Tezos operations we use the Tezos index, but as we use taquito to download data at #120 the hashes come as a string which need then to be converted to a BLAKE2B.
This adds direct support to Operation_hash on Tezos_interop as a `BLAKE2B.t`.
- #34 
- #61

support Operation_hash on Tezos_interop

---

bin/http_server.re

Currently http_server logs only a few of the available error messages, this makes it quite hard to debug simple mistakes.
This is just an improvement, it prints all the errors explicitly on the http_server module.
- #64

improve http_server error handling

---

bin/files.re
bin/files.rei
bin/http_server.re

To produce-blocks a state.bin is required, but to start the chain you need to produce a block, so currently there is no way to start a fresh chain.
When starting a node we always ensure there is a state.bin present, if there is none one is created with a state with the genesis state.
- Closes #121

create state.bin when not present

---

protocol/address.re

Currently we're using b58 to represent Tezos secret but just hex encoding to represent Address.key which means for the same thing, an ed25519 secret key we have two encodings.
Move everything to b58 as it is a well established standard. Here the prefix is `edpk`.
```reason
Tezos_interop.Base58.(
simple_encode(
~prefix=Prefix.ed25519_seed,
~to_raw=Fun.id,
Hex.to_string(`Hex("key_hex_here")),
)
)
```

use b58 to represent Address.key

---

tests/test_ledger.re
tests/test_protocol.re
tests/test_tezos_interop.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

KT1's in Tezos can actually have an entrypoint in the form of `KT1address%entrypoint`, this is currently not supported by sidechain and it's important to parse Tezos address on #61
Here we integrate the entrypoint on `Originated` under `Address.t`, this is not the best solution as technically Tezos supports entrypoints on tz1 but as it's not used anywhere so we just ignore it for now. If this is ever a thing we may need to change some code.
- #34 
- #61

support entrypoint on KT1

---

esy.lock/index.json
esy.lock/opam/digestif.1.0.1/opam
esy.lock/opam/duration.0.2.0/opam
esy.lock/opam/lwt.5.4.2/opam
package.json
tezos_interop/dune
tezos_interop/listen_transactions.js
tezos_interop/webpack.config.js

To achieve automatic deposit detection required by #34 we need to listen for operations on Tezos.
This is a step on that direction, as Tezos doesn't provide a socket like API and I don't want to reimplement the polling logic already present in Taquito we just use Taquito to make a CLI, this CLI will accept the context on the `stdin` and each line on `stdout` is a transaction.
Operation hash is not enough to index a Tezos operation as the internals operations share the same hash, that's why I also include an index based on the operation result, as this should be reliable(result hash is checked by tezos) we can trust it to be in order and all nodes to agree on the index.
- #34 
- #61

add JS script to listen for transactions

---

bin/sidecli.re

- #123 
`setup-identity` exists and `setup-node` also generates a new identity which overrides the current identity.
Instead of making `setup-node` consumes `setup-identity` the idea here is to split `setup-node` in sub commands, `setup-tezos` and `setup-identity`. This PR adds `setup-tezos` as a way to setup the `tezos.json`.

add setup-tezos command

---

protocol/address.re

- #124 
Essentially the same as #124 but about Address.t, we use hex instead of b58 without a good reason.
Move everything to b58 as it is a well established standard. Here the prefix is `edpk`.
```reason
Tezos_interop.Base58.(
simple_encode(
~prefix=Prefix.ed25519_public_key,
~to_raw=Fun.id,
Hex.to_string(`Hex("t_hex_here")),
)
)

Address.t pub keys as b58

---

protocol/operation.re
protocol/operation.rei
tests/test_protocol.re

At #120 we found out that main chain operations require more than just a tezos_hash, but also a tezos_index, which is currently not implemented and is required to future integrations.
This refactors the main chain operation to include a tezos_index but also adds a hashing so that in the future integration we can verify if the main chain operation is known easily.

refactor main chain operations

---

tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

To achieve #34 and #61 we need to be able to listen to deposit operations that happens on Tezos.
This is a step on this direction, by integrating Tezos_interop on the `listen_transactions.js` script added on #120. We can in the future use this function to 
detect operations happening Tezos.
- #34 
- #61

 add Consensus.listen_operations on Tezos_interop

---

node/building_blocks.re

Because of the protocol was designed originally on the assumption that all main chain operations were confirmed, currently the block producer can include an operation and we will never verify it.
Instead of verifying it, as the integration with Tezos is not reliable, we just avoid signing a block if it includes an unknown main operation. That means if 2/3 of the chain signs, it will still be applied but a validator will never signs an unknown main operation.

Defend against unknown main operation

---

node/state.re
protocol/protocol.re
protocol/state.re
tests/test_protocol.re

Currently an operation can be added two times in a block and it will be applied, this is not the desirable as it allows to multiply money.
Do the same as for Operation.Side_chain, have a list of included main operations on the protocol state. The only difference is that this will never be cleaned as there is no such a thing as a maximum block_height on main operations.

Prevent replay attack on main operations

---

node/building_blocks.re

To keep the PR graph simple
There is a bug on the cleaning logic where all operations that are in the block are kept on the pool, but all other operations are removed, the opposite should happen.
Fix the bug and refactor a bit this block, it's still is bad but now it does the right thing.

properly clean operations after applying block

---

bin/sidecli.re
protocol/address.re
protocol/address.rei

Currently the only way to verify your identity is by checking inside of the `identity.json` but this is an implementation detail and should not be relied upon.
This PR implements a `self` command that will print your key, address and uri so that we can easily awk it and be a bit more future proof.

add self subcommand

---

README.md

The readme contains information about esy lock files that is no longer up to date
Remove that section

Readme: remove inaccurate section about lock files

---

bin/http_server.re
node/flows.re
node/networking.re
protocol/protocol.re

Currently we do not provide a way to check balance of an address, so the only way to know if there is balance available is to make a transaction from the address.
Implement an endpoint to check the ticket balance based on the ticket id.
```json
POST /ticket-balance
{
"address": "tz1NJ8q6qunwi2Thx4MxtVtMXixTtcJcXL5q",
"ticket": {
"ticketer": "KT199KwMHcpnmroMMYWwKUtZz2fygX18yDYz",
"data": ""
}
}
```

ticket balance endpoint

---

bin/sidecli.re

Currently sign-block requires a `wallet.json` but this sign-block is needed to spawn a chain, but `wallet.json` should not be required to spawn a chain.
Makes `sign-block` expects only a folder with `identity.json` like `produce-block`.

sign-block expects only a node folder

---

setup.sh

Currently you need to create a couple files by hand to setup a node, and also deploy the consensus contract, currently this is not automated at all.
Here we make a script, that will prompt you to deploy the contract and create all the files needed after you deploy the contract.
This is based on @callistonianembrace work at:
- #111

add script to easy setup

---

bin/http_server.re
bin/sidecli.re

Currently the validators order loaded in the node is reversed of the `validators.json`, but the order matters to the Tezos contract.
Fix the ordering on the load, in the future this will be done different as per @callistonianembrace work.

fix the validators ordering

---

bin/http_server.re
bin/sidecli.re

We need a simple way to trigger withdraws on the sidechain so that they can be used in the future to construct a proof and be withdraw on Tezos.
This commands implements the withdraw command in a similar manner to `create-transaction`
```sh
esy x sidecli withdraw data/0 ./wallet.json "tz1QTt4YksnwfDnvu7eFGWdEu7gEyZgnc3Vk" 32 'Pair "KT199KwMHcpnmroMMYWwKUtZz2fygX18yDYz" 0x'
```
- #164

add CLI withdraw command

---

helpers/BLAKE2B.re
node/state.re
node/state.rei
protocol/protocol.re
tests/test_protocol.re

To achieve #164 we need to somehow get the handle for an operation, but this is only known after the operation is applied, which currently means the result of the operation is lost.
In this PR we store it temporarily(during the node execution), so that it can be requested in a future PR from the operation hash.
- #164

store operation results temporarily

---

bin/http_server.re
bin/sidecli.re
node/flows.re
node/networking.re
protocol/ledger.re
protocol/ledger.rei

At #167 we provide a command to make tickets withdraw easily but there is no simple way to use this and actually withdraw the tickets on Tezos.
Here we provide a command that will give you a piece of michelson to be sent to the `%withdraw` entrypoint on the consensus contract.
```sh
esy x sidecli withdraw data/0 ./wallet.json "<OWNER>" <AMOUNT> 'Pair "<TICKETER>" 0x<DATA>'
HANDLE=$(esy x sidecli withdraw-proof data/0 <OPERATION_HASH> <CONTRACT_CALLBACK>)
tezos-client transfer 0 from <OWNER> to <CONSENSUS_CONTRACT> --entrypoint "withdraw" --arg "$HANDLE"
```
- Closes #164

add withdraw-proof command

---

tezos_interop/dune
tezos_interop/fetch_storage.js
tezos_interop/listen_transactions.js
tezos_interop/run_entrypoint.js
tezos_interop/tezos_interop.re
tezos_interop/webpack.config.js

We manually generate validators.json with sh scripts on the client, where as the deployed `consensus.mligo` should be the source of truth.
This PR adds a Taquito script that inspects a contracts storage.  `module Fetch_storage` that fetches the storage and return it as michelson.

Adds a Taquito script to fetch contract storage

---

tezos_interop/tezos_interop.re

Currently the `Fetch_storage.run` function is creating a temporary file on every call, this file is identical for every execution so it should be created only once.
Move it to the global scope of the module, so that it's created during the boot of the application
- #157

create fetch_storage script on boot only

---

protocol/operation.re
protocol/operation.rei
protocol/protocol.re
tests/test_protocol.re

We have unused mainchain ops - Add_validator and Remove_validator
This PR remove the said unused mainchain ops

Removes unused mainchain_ops: add/remove validators

---

bin/sidecli.re

Changes "transact" to "transfer", as I believe this wasn't standard usage.
Also corrects a typo.

correct wording and typo in CLI

---

bin/http_server.re
tezos_interop/fetch_storage.js
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

We manually generate validators.json with sh scripts on the client, where as the deployed `consensus.mligo` should be the source of truth.
This PR uses the Taquito script from #157 to fetch the validators set

Fetch validators from consensus contract

---

node/flows.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

We don't have a way to know if the node is in sync with the mainchain
This PR (along with #175 ), adds the ability to parse `update_root_hash` operations, so that updates to state root hash published to the main chain can be listened in, which would help a node know if it is in sync with main chain or not.

Parse `update_root_hash` operation  from the mainchain

---

bin/sidecli.re
node/networking.re

Clients like sidecli broadcast the network operations themselves. 
This PR directly posts operations to `/operation-gossip` endpoint as using http endpoints meant inter-node communication can also be used by sidecli
- closes #70

Avoids broadcasting operations from sidecli

---

bin/deku_node.re
bin/files.re
bin/files.rei
bin/sidecli.re
node/state.re
node/state.rei
node/trusted_validators_membership_change.re

Add_validator operation needs to be verified against a list of trusted validators that a node operator maintains/obtains off-chain.
This PR adds a new entry in the node state - `trusted_validators` - which a node sources from `trusted-validators.json`. This files is expected to contain keys and URIs of validators that a node operation doesn't mind being added to the chain as a validator in the future

Adds trusted_validators in the node-local state

---

HACKING.md

We currently don't have a place to aggregate style requirements. We need one so as to not slow down PR's with things that could be easily addressed ahead of time. 
Adds a section to the HACKING.md document.
Note I don't know what the preference is for handling promises that invoked purely for side effects, so we need to address the `FIXME:` before merging.

Add an OCaml Style Guide

---

bin/sidecli.re
protocol/operation.re
protocol/operation.rei
protocol/protocol.re
tests/test_protocol.re

Every operation is currently associated with an amount and a ticket. This is no longer true after #182 - some sidechain operations, `Add_validator`, `Remove_validator` etc don't need these properties.
This PR move these fields to `Withdraw` and `Transaction` operations only where they are needed

proto: move amount and ticket to operation kind

---

.github/pull_request_template.md

All PRs should have some basic elements so that writing a PR doesn't involve taking too many decisions, this is currently a recommendation on the README, but that is not really discoverable, also there is some details in the github flavored markdown which improves the PR description layout.
This adds a simple PR template for future use.
- closes #161

add github PR template

---

protocol/ticket.re
tests/test_ledger.re

There is a subtle bug on the `compare` function for tickets, which lead to it always being `== 0` even if the ticketer was different. Making so that one could get one unit of a ticket, make another ticket with the same data and that would fuse with the first ticket, allowing essentially to multiply it's own ticket amount and then essentially withdraw someone else ticket from the consensus contract.
Fix the comparison and implement some tests to avoid any regression, after implementing I noticed that a test was actually broken but it was not triggering due to the bug above.

fix ticket comparison

---

helpers/BLAKE2B.re
tests/test_tezos_interop.re
tezos_interop/dune
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

We use polymorphic equality operators on tezos interop now
This PR adds specialized equal fn to modules in Tezos_interop.

Add explicit equal fn to Tezos_interop

---

crypto/crypto_intf.re
protocol/signature.re
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Since #238 we're not using mirage-crypto-ec directly, but we're still exposing the types to the codebase and not using abstract types so mixing things like `signature` and `message` is possible.
To avoid simple mistakes like using mirage-crypto-ec types outside of the crypto library, this PR makes `Ed25519.{Key,Secret,Signature}` abstracts, this also solves the problem of `Signature.t` being a string.

Abstract Ed25519.{Key,Secret,Signature}

---

package.json

Esy's package.json esy.release.bin field "helps esy figure which binaries have to be made binary relocatable and ready for publishing to NPM" (thanks @callistonianembrace for explaining that). But it doesn't currently contain `deku-node`.
Add `deku-node`

add deku-node to package.json's esy.release.bin

---

bin/deku_node.re
bin/dune
bin/sidecli.re
crypto/crypto.re
crypto/dune
protocol/dune
tests/dune
tests/setup.re
tests/test_runner.re
tezos_interop/dune

mirage-crypto-rng which is used by mirage-crypto-ec needs to be initialized with a random generator before any other crypto call happens, this leads to a problem where we initialize the RNG in many places.
Because the crypto module needs to be initialized before any crypto function can be used it creates a nice spot to do RNG initialization, and this is what I do on this PR.
As a bonus I remove all the external mentions to mirage-crypto.

initialize rng inside of crypto

---

protocol/block.re
protocol/validators.re

Currently we update the validators hash only when the state root hash updates, in the past I thought this was required but after rethinking, we can easily update the validators a lot more frequently than the state root hash as the proof of the consensus is actually the block hash.
As validators rarely change, we can compute the hash when adding or removing a new validator and just use the same hash. This allows to update the validators hash on every block.
- #227

Precompute validators hash

---

crypto/crypto.rei
crypto/key.re
crypto/key.rei
crypto/key_hash.re
crypto/key_hash.rei
crypto/secp256k1.re
crypto/secret.re
crypto/secret.rei
crypto/signature.re
crypto/signature.rei
protocol/address.re
tests/test_tezos_interop.re
tezos_interop/tezos_interop.re

we don't support tz2 addresses in the tezos_interop
add tz2 support
withdrawal and deposit operations do work: 
- deposit -> https://better-call.dev/granadanet/opg/oo6MguGzqkXrMMLm9kAt2hok4S33ZEgr8zu9KwkjFiGLAbxxdkm/contents
- withdraw -> https://better-call.dev/granadanet/opg/opJ31n64dVVDeYyYtEUV7pxDKwnQF4q3Ku4KXEPVHNpsHReVkSD/contents
- #22 
- #199

Tz2 support

---

crypto/crypto.rei

Running Crypto.Ed25519.generate() fails due to uninitialized random generator
pass the generator instance explicitly

fix random generator error

---

bin/deku_node.re
bin/dune

The node does not use cmdliner. That means if you just run the node and pass no arguments you get a pretty unhelpful error message. 
```
$ esy x deku-node
Fatal error: exception (Invalid_argument "index out of bounds")
```
Use cmdliner to process the command line arguments. Now the error is much more explanatory:
```
$ esy x deku-node
deku-node: required argument folder_node is missing
Usage: deku-node [OPTION]... folder_node
Try `deku-node --help' for more information.
```
I'm not sure that `folder_node` is the right name (I just copied it from sidecli), feel free to change it.
Also this helps with the logging PR. Cmdliner comes with built-in combinators for handling logging (e.g. changing the verbosity, enabling or disabling the colors, etc.) which we use in sidecli currently but can't …

Use cmdliner for node

---

bin/deku_node.re

The `deku-node` binary is broken. It double-prepends the `--folder` path when looking for `trusted-validator-membership-changes.json` and then fails when it can't find it.
Fix the path. I did this by moving the place where we specify the path next to all the other places so it's more obvious what the path should be, preventing this mistake from happening again in the future.
NA

Fix trusted-validator-membership-changes.json path

---

crypto/crypto_intf.rei
crypto/ed25519.re
crypto/secp256k1.re
crypto/signature.re
crypto/signature.rei
protocol/block.re
protocol/protocol_signature.re
tests/test_tezos_interop.re
tezos_interop/tezos_interop.re

Currently `Signature.{sign,verify}` accept any message, but this is not correct, a Deku node should always sign only a hash(BLAKE2B), this also reflects the behavior at Tezos where [CHECK_SIGNATURE](https://gitlab.com/tezos/tezos/-/blob/cf95d1507a13efb3ff4fb247aabb44efc0082fa7/src/lib_crypto/ed25519.ml#L338) always hashes the message before.
This PR guarantees that on the type level by making so that the functions accept a hash directly. Because of that this removes the double hashing for a lot of operations, but for communication with Tezos it is still needed as seen at [consensus.mligo](https://github.com/marigold-dev/deku/blob/4798b2e221280036a389233000a1d600cd530317/tezos_interop/consensus.mligo#L64) where we first hash it, then pass to `Crypto.check` which will hash it again.

crypto: Signature.{sign,verify} accepts a hash

---

bin/sidecli.re

We need a way to lower the required Tezos confirmations for doing local development and testing. However, this way should be clearly labeled as dangerous and not production-worthy.
Add a CLI option prefixed with `unsafe`.
This PR supersedes #280

Add command line option for setting the required confirmations on setup

---

bin/sidecli.re
protocol/ticket.re
protocol/ticket.rei
tests/test_tezos_interop.re
tezos/dune
tezos/tezos.re
tezos/tezos.rei
tezos/ticket_id.re
tezos/ticket_id.rei
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Following #303, a tezos ticket is also currently defined inside of Tezos_interop, and should be at the Tezos library, there is also the fact that a `Ticket.t` is actually an `Ticket_id.t` as it only represents the identification part of a Ticket.
This PR refactors the Ticket module a bit, renames it to `Ticket_Id` and move it to the Tezos library.

tezos: move Ticket_id from Tezos_interop

---

protocol/operation.re
protocol/operation.rei
tezos/operation_hash.re
tezos/operation_hash.rei
tezos/tezos.re
tezos/tezos.rei
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Finishing what #303 started, an operation_hash is currently defined inside of Tezos_interop, but it should be conceptually inside of the Tezos library. It also lacks some basic utils like serialization and comparison.
This refactors the Operation_hash module and moves it to the Tezos library.

tezos: move Operation_hash from Tezos_interop

---

node/block_pool.re

Currently we don't add genesis to the block pool. This leads to the node trying to fetch the genesis block over the network, which is triggered by #227.
Add genesis to the block pool as part of `make`.
- #227

Add genesis block to the block pool on init

---

bin/deku_node.re
node/flows.re

There is a problem with the current block-fetching algorithm that causes the node to search for blocks it has already applied.
Add a check to prevent this.
Additionally, to make it easier to interpret the error messages, I alphabetized the error variants.

Don't search for blocks with lower block height

---

bin/sidecli.re
node/flows.re
node/state.re
node/state.rei

`State.identity` currently refers to a secret as `key` which is wrong. Also `State.identity` doesn't have a key, which makes so that in some places we do `of_secret`, which is not a free operation.
Rename `State.identity.key` to secret and add a `key` field on `State.identity` to replace the occurrences of `of_secret(identity.t)`.

Refactor identity state

---

node/flows.re
node/state.re
protocol/protocol_signature.re
protocol/protocol_signature.rei

Right now we're hashing the public key quite often due to Protocol_signatures not containing an address.
Just add an `address` to Protocol_signatures and separate the serialization from the internal representation. Also some dead functions were removed.

refactor: Protocol_signatures should contain an address

---

ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/contracts/make_an_option.religo
ligolang/src/test/zinc_test.ml

There was no way to construct the option variants `None` or `Some` in usercode
Add implementations for the necessary constants  - also had to implement unit literals.
Work remains to be done to add support to the interpreter

Ligo: Add support for compiling options to zinc

---

ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/contracts/make_a_custom_option.religo
ligolang/src/test/contracts/make_an_option.religo
ligolang/src/test/zinc_test.ml

Previously it was not possible to construct custom variants (before #319 no variants could be constructed, and after only options could be constructed). 
Allow custom user variants to be constructed
Same as #319, this change does not enable interpreter support for variant constructors. Additionally, `match` will not yet work with these variants.

Ligo: add support for constructing custom zinc variants

---

bin/sidecli.re

`add-trusted-validator` and `remove-trusted-validator` wrongly mention `validator_address` as 3rd positional argument
This PR fixes the issue by making them 2nd positional argument
- #206

sidecli: Fix validator_address arg position

---

tools/dune

Installing Deku need not install the custom repl meant for development. `esy release` is broken because it tries to build the REPL which contains only development dependencies
This PR makes `dtop` private and local to project
#315

dune: make dtop.exe private

---

crypto/random.re
crypto/random.rei
node/building_blocks.re

Currently the `find_random_validator_uri` function is using `int32` directly from the `Stdlib.Random` instead of `Crypto.Random` this may be problematic as the RNG is initialized implicitly.
This PR fixes that by adding `Random.int32` to `Crypto` and using it directly on `building_blocks.re`

fix: use Crypto.Random instead of Stdlib.Random

---

zinc/lib/Zinc_interpreter.ml

As of #321, custom variants are supported by the Zinc compiler, but not by the Zinc interpreter (and hence, their tests are currently failing).
Add a match case to the interpreter that constructs a custom variant and pushes it to the stack
- #328

zinc: add custom variants to zinc interpreter

---

node/flows.re

`remove-trusted-validator` is supposed to help us add a removal membership to the trusted list. (in retrospect, the command name is a misnomer too)
This PR corrects adds the mechanism to add validator removals to the trusted list

fix: trusted membership flow must add not remove

---

protocol/block.re
protocol/ledger.re
protocol/validators.re
tests/test_tezos_interop.re
tezos/deku.re
tezos/deku.rei
tezos/tezos.re
tezos/tezos.rei
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

The hash functions described at `Tezos_interop.Consensus` are crucial for the core state machine of Deku but they currently live inside of `Tezos_interop` which is a library designed to describe IO communication with Tezos.
Move the hashing functions to `Tezos.Deku.Consensus` so that it can safely be used inside of the core.

refactor: move consensus hashing to Tezos.Deku

---

ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/zinc_test.ml
zinc/lib/Zinc_interpreter.ml
zinc/lib/Zinc_types.ml
zinc/tests/test_sample.ml

Every zinc instruction was just sitting in `Zinc_instruction`. 
We can improve the organization by splitting it into multiple smaller types.
- closes #347

Reorganize zinc primitives 

---

ligolang/src/test/zinc_test.ml

Currently, Zinc tests take as a parameter whether or not the contract is written in Reason LIGO or not, which affects the file extension of the contract file that the test searches for. This is not as flexible as it should be, since test contracts may come in any dialect of LIGO.
Create an enum for representing dialects in the test file, and make dialect a parameter of the `expect_simple_compile_to` function. Default to PascaLIGO and determine file extension based on dialect. Change all tests where `~reason` was true to explicitly set their dialect to `Reasonligo`.

Made LIGO dialect a test parameter

---

ligolang/esy.lock/index.json
ligolang/esy.lock/opam/coq.8.13.1/files/coq.install
ligolang/esy.lock/opam/coq.8.13.1/files/disable_warn_70.patch
ligolang/esy.lock/opam/coq.8.13.1/opam
ligolang/package.json

Older overrides wouldn't install coq artifacts correctly. 
Fixed and upstreamed the overrides [here](https://github.com/esy-ocaml/esy-opam-override). This PR removes local overrides for coq so that the upstream repo is looked into for overrides.

esy: use coq overrides from esy-opam-overrides

---

ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/contracts/top_level_let_dependencies.religo
ligolang/src/test/zinc_tests.ml

Pointed out to me by @Zett98 - there was a bug in how we convert top-level-lets into single expressions. The idea is to convert this:
```reason
let a = 1;
let b = a;
let c = 1;
```
to this:
```reason
let a = 1;
let b = let a = 1 in a;
let c = let a = 1 in let b = a in 1;
```
That way each top-level let is self-contained. But the logic was wrong, and the conversion was actually doing this:
```reason
let a = 1;
let b = let a = 1 in a;
let c = let b = a in let a = 1 in 1; // Order got flipped
```
Which doesn't compile haha.
Correct the order

Ligo: Fix top level let dependency order

---

sandbox.sh
start.sh

The `./sandbox.sh tear-down` is not removing old data and the `./start.sh` is currently starting too fast.
Fix the tear-down flow of `sandbox.sh`. Also increase the start script delay to one second, this is required due to the fact that starting the node is now slower as it needs to talk to a Tezos node.

fix sandbox and start script

---

ligolang/.ocamlformat-enable
ligolang/src/passes/13deku-zincing/compiler.ml

I've convinced the ligo team to enable ocamlformat on an opt-in, whitelist basis, so now we can whitelist our files to keep them formatted. I added zinc_tests already to the whitelist already, so this MR adds compiler.ml

Enable ocamlformat on the zinc compiler

---

ligolang/.ocamlformat-enable
ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/contracts/if_then_else.religo
ligolang/src/test/contracts/if_then_else_op.ligo
ligolang/src/test/contracts/if_then_else_op_function.ligo
ligolang/src/test/zinc_tests.ml
zinc/lib/zinc_interpreter/Zinc_interpreter.ml

#356
#330 added booleans and if/else to zinc and to the compiler, but not to the interpreter. The tests also did not catch this because none of them were testing the interpreter due to confusing defaults in the test function
Add support for if/else to the interpreter. A good test to add would be to ensure that it's lazy - it is lazy, but there's no test for it yet. 
Also, change the `expect_simple_compile_to` function to default to executing the *last* binding, rather than the first one.

Add if/else to the zinc interpreter

---

bin/deku_node.re
bin/sidecli.re
node/flows.re
node/networking.re

Currently the `/operation-gossip` endpoint is used for both `consensus` operations(adding and removing validators) and also for `user` operations, like transactions and withdraws. This will be problematic in the future when we proper split the operations per group.
This PR makes two new endpoints `/user-operation-gossip` and `/consensus-operation-gossip`, each responsible for it's own kind of operations.

networking: {user,consensus}-operation-gossip endpoints

---

bin/deku_node.re
node/flows.re
tezos_interop/listen_transactions.js
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

An operation on Tezos may actually trigger many Tezos internal operations, currently the script `listen_transactions.js` dispatch each one of those internal operations individually, which is problematic as it allows to apply only a portion of all Tezos internal operations in a single hash.
Also it doesn't model well how Tezos operations happens and the script is supposed to be a low level solution.
Dispatch all Tezos operations in a single entry instead of multiple entries. Then internally this is dispatched to multiple protocol operations.

tezos_interop: parse tezos operation as batch

---

ligolang/src/passes/13deku-zincing/compiler.ml
ligolang/src/test/contracts/custom_variant_matching.mligo
ligolang/src/test/zinc_tests.ml
zinc/lib/zinc_interpreter/Zinc_interpreter.ml
zinc/lib/zinc_interpreter/Zinc_interpreter.mli
zinc/lib/zinc_types/Zinc_types.ml
zinc/lib/zinc_types/zinc_types_intf.ml
zinc/lib/zinc_utils/Zinc_utils.ml
zinc/tests/test_sample.ml

Currently variants are represented as `(string * Zinc.t) list`, and we can't match on custom variants
change their representation to `Zinc.t Array.t`, and allow matching on custom variants
- #358

change variants representation

---

.github/workflows/docker.yml

This change will make sure we push new versions when a new push to main happens
We don't push deku images to the docker registry
Fix the typo in the check so that it evaluates to true on the `main` branch

Fix typo in docker workflow

---

README.md
flake.lock
flake.nix

There's no way to build Deku in Nix/NixOS.
Additionally, it would be nice to have the advantages nix provides (reproducible, declarative setup, etc).
This PR adds a nix flake for a completely reproducible nix setup.
It's not full nix support, since nix and esy are not compatible. Instead, we use nix
to build a chroot environment with esy installed (this is how Steam and VS Code work on NixOS) .
Users can just do `nix run` to get dropped into an environment with esy installed, and then
do esy development workflow as usual. Additionally, we can install any nix package we want
by adding to the `extraPackages` list - notice `ligo` is installed this way.

Add nix flake support

---

tezos_interop/tezos_interop.re

There is currently no easy way to tell whether the block producer is actually communicating with the main chain or not.
This PR adds a log to make it clear.

Add logging of run_entrypoint.js output

---

.github/workflows/docker.yml

We are trying to push images to the hub.docker.io registry since that is the default but we're not authenticated with it
We already authenticate with the github registry so we just had to ad `ghcr.io/` to the beginning of the tags.

Push docker image to correct registry in CI

---

node/state.re
protocol/protocol_signature.re
protocol/protocol_signature.rei
tezos_interop/consensus.mligo
tezos_interop/tezos_interop.re
tezos_interop/tezos_interop.rei

Deku communication with the main chain is broken in two different ways on main:
1 The `current_validator_keys` introduced to consensus.mligo in #208 is not being sent by the Deku node
2 Ignoring that problem, Deku signatures are not recognized as valid by the main chain.
- This latter point bears explanation. Conceptually, validators sign block hashes to show their approval of that block. But starting in #302, we replaced block hashing with a function that hashed the block twice. Thus validators started signing not the hash(block), but the hash(hash(block)). This was done to match the behavior of `CHECK_SIGNATURE` in Tezos, as mentioned in the PR. However, this introduced a bug - when sending the `block_hash` parameter, we were sending not the `hash(block)` but the `hash(hash(block))`. …

Fix main-chain communication

---

core/amount.re
tests/test_ledger.re

We shouldn't be able to represent negative amounts. The previous code contained an assertion, a more explicit exception is probably better. Also, tests.
Raise an Invalid_argument when trying to represent a negative amount.
- Closes #399

Exception for negative amounts (issue #399)

---

bin/deku_node.re
bin/dune
bin/files.re
bin/node_state.re
bin/node_state.rei
bin/sidecli.re
crypto/incremental_patricia.re
node/building_blocks.re
node/flows.re
node/snapshots.re
node/snapshots.rei
node/state.re
node/state.rei
protocol/block.re
protocol/block.rei
protocol/protocol.re

Per #147, we want async state hashing. We have a design in #218; however, the problem remains a complex one, and we need to break apart the design in to incremental steps. This PR avoids asynchronicity, and instead introduces the smallest step possible in the right direction: the delayed state hashing.
Recall that #218 introduces the new terminology of "state root epoch" to refer to the interval (in blocks) between state root hash updates. This PR delays the state root hash sent by one epoch, such that the next state root hash N is calculated during epoch N - 1 (refer to #218 for diagrams illustrating this).
To achieve this, we extend the protocol state with a fields `current_epoch` and `next_epoch`. `current_epoch` is merely an integer identifier for the epoch (that will be used in …

Delayed State Hashing

---

node/flows.re
node/state.re
protocol/protocol.re

Per #147, we're trying to achieve async state hashing. But this is a complex problem (see #218). 
Before we make hashing async, we first need to lift the process of hashing out of the protocol and into the node. 
Remember, `./protocol` does not actually do consensus - rather, the `Protocol` library contains just the core state information  that is guaranteed to be agreed upon by every honest in-sync node. Therefore, any consensus checking should be done in `./node` - any checking done in `./protocol` is only as a redundancy/failsafe.
This change should not modify the behavior in any way from #227 (reviewers, help me check this!). All it does is move the hashing process to `Node.State.apply_block`. In the next  PR, we'll introduce (partial) asynchronicity. 
- #147

Lift state hashing to the node

---

bin/deku_node.re
bin/node_state.re
node/building_blocks.re
node/flows.re
node/networking.re
node/snapshots.re
node/snapshots.rei
node/state.re
node/state.rei

This PR is another step towards #147. 
The problem is that we currently only store two snapshots: the latest in `state.snapshot` and the next one in `state.next_state_root`. With async state hashing we may need to store more. 
To accomplish this, we push all snapshot logic into the snapshots module, removing the `next_state_root` property from the node state. We store all snapshots in a map, along with pointers to the current and next snapshot. We then move those pointers on each epoch.

Store a list of snapshots

---

ppx_let_binding/.ocamlformat
ppx_let_binding/dune
ppx_let_binding/ppx_let_binding.ml
ppx_let_binding/test/dune
ppx_let_binding/test/ppx_let_binding_test.ml

We want to migrate to OCaml syntax, but OCaml syntax does not support the custom let bindings that Reason does.
This PR adds a PPX that allows users to define custom let expressions a la Reason. The only difference is that you have to replace the `.` with a `%` when you use the let expression
One issue is that we couldn't figure out a simple way to dynamically register the syntax extensions. Thus, we simply hard-coded a list of extensions to check for (the ones we currently use). This list can easily be extended, or if someone wants to put in the work to make it cleaner/more dynamic, they certainly can. But we felt this was good enough for a first pass.

Ppx let binding

---

src/bin/files.re
src/bin/files.rei
src/bin/node_state.re
src/bin/sidecli.re
src/core/address.re
src/core/address.rei
src/core/ledger.re
src/core/ledger.rei
src/core/state.re
src/core/user_operation.re
src/core/user_operation.rei
src/crypto/key_hash.re
src/crypto/key_hash.rei
src/node/flows.re
src/node/networking.re
src/node/state.re
src/node/state.rei
src/node/trusted_validators_membership_change.re
src/protocol/block.re
src/protocol/block.rei
src/protocol/protocol_operation.re
src/protocol/protocol_signature.re
src/protocol/protocol_signature.rei
src/protocol/validators.re
src/protocol/validators.rei
tests/test_ledger.re
tests/test_validators.re

Currently, address is assumed to be an implicit address. But now that we're adding contracts, an 'address' could also be a contract address. But most places of the code that talk about addresses currently really mean to talk about implicit addresses. 
Move `Protocol.Address` into `Protocol.Address.Implicit`. Then, almost everywhere that currently references `Protocol.Address` should now reference `Protocol.Address.Implicit`.

Split address into implicit and contract address

---

src/bin/deku_node.ml
src/node/flows.ml

1. `print_error` should be re-usable in several modules
1. `print_error` is missing a few kinds of errors producable by the node
1. When we load snapshot, we supress errors, which is bad when debugging/troubleshooting.
1. Our error messages are just plain white text, no formatting. Lame.
1.  Moved  function.
1.  Added missing errors
1. Use `print_error` to print errors when loading a snapshot.
1.  Add some formatting to the error message to make it stand out.

Refactor: move print_error from deku_node to flows

---

src/bin/sidecli.ml
src/core/ledger.ml
src/core/ledger.mli
src/core/state.ml
src/core/state.mli
src/node/flows.ml
src/node/networking.ml
src/protocol/block.ml
src/protocol/block.mli
src/tezos/deku.ml
src/tezos/deku.mli
src/tezos_interop/tezos_interop.ml
src/tezos_interop/tezos_interop.mli
tests/test_tezos_interop.re

Soon, we'll add a ticket table (#388), which will create a notion of "ticket handles". This conflicts with the current usage of "handle", which currently refers to the handles used for withdrawal.
Rename all current usages of "handle" to "withdrawal_handle"

Rename `handle` to `withdrawal_handle`

---

src/tezos/michelson.ml
src/tezos/michelson.mli
src/tezos/operation.ml
src/tezos/operation.mli
tests/test_tezos_interop.re

On Tezos there is no distinction between parameters being empty, and a parameter that has entrypoint of `default` and value of `unit`, this is currently not the case on Deku.
This can be verified at [operation_repr.ml](https://gitlab.com/tezos/tezos/-/blob/40c795e414f9a799bf0af3312e0efd264a1231d9/src/proto_alpha/lib_protocol/operation_repr.ml#L440)
Changing the API to represent this and also handling the checking on the encodings like how Tezos is doing. I also added another test extracted from Taquito calling a contract.

tezos: fix Operation.forge with default + Unit

---

src/tezos_rpc/dune
src/tezos_rpc/error.mli
src/tezos_rpc/http.ml
src/tezos_rpc/http.mli
src/tezos_rpc/inject_operations.ml
src/tezos_rpc/inject_operations.mli
src/tezos_rpc/tezos_rpc.mli

As mentioned at #429 ideally we should move away from Taquito, for this one of the requirements is that we need to be able to inject operations on Tezos.
This PR exposes `Tezos_rpc.Inject_operations.execute` to actually inject the operations on the chain, under the hood it uses #429 work to make the HTTP requests to a Tezos node.
This also defines the `tezos_rpc` library to be extended in the future.

tezos_rpc: library and /inject-operations

---

src/bin/deku_node.ml

On some machines, Dream binds directly to localhost, which is on ipv6, but some software treats localhost as always 127.0.0.1, which makes the connection to fail.
Bind on all interfaces using `0.0.0.0`.

node: bind to all interfaces

---

src/tezos_interop/tezos_interop.ml

As of #431 Deku main is broken when talking to Tezos due to a JSON change.
This is the conservative solution, instead of changing it also on the consensus.mligo contract we just revert the change for this specific JOSN field.
In the future we should use ocaml-to-ligo to prevents mistakes as this.

tezos_interop: fix consensus.mligo integration

---

src/node/snapshots.ml
src/protocol/protocol.ml
src/tezos_interop/tezos_interop.ml

If you stop the chain when it's time for a new protocol hash, `sidecli produce-block` will print an additional message on stdout, which breaks `./start.sh`.
For now this PR makes so that we use stderr for logs, in the future we should have a proper logging solution.
This PR also improves the messages a bit.

chore: use stderr for logs

---

src/crypto/base58.ml
src/crypto/base58.mli
src/tezos/chain_id.ml
src/tezos/chain_id.mli
src/tezos/tezos.ml
src/tezos/tezos.mli
src/tezos_rpc/fetch_block_operations.ml
src/tezos_rpc/fetch_block_operations.mli
src/tezos_rpc/tezos_rpc.mli

Similar to #444, another requirement to move away from Taquito is to be able to fetch the operations of a block, to detect interactions with `consensus.mligo`.
Implements `Tezos_rpc.Fetch_block_operations`, this API provides a way to fetch the operations from a specific chain and block_hash.
**warning**: the implementation is not ideal as the JSON encoded by Tezos is quite complex, so this PR just abuses of `ppx_deriving_yojson` to generate some simplified decoders, in the current stage this only decode transactions and internal transactions.

tezos_rpc: Fetch_block_operations

---

src/tezos_rpc/fetch_block_header.ml
src/tezos_rpc/fetch_block_header.mli
src/tezos_rpc/tezos_rpc.mli

Following #447, in the missiong of moving away from Taquito, sometimes we may not receive a block, because the connection with the Tezos RPC was temporarily broken, so we need to be able to fetch old blocks header.
Implements `Tezos_rpc.Fetch_block_header`, this will call Tezos asking for an specific block header.

tezos_rpc: add Fetch_block_header

---

src/helpers/dune
src/helpers/yojson_ext.ml
src/helpers/yojson_ext.mli
src/tezos/gas.ml
src/tezos/gas.mli
src/tezos/tez.ml
src/tezos_rpc/fetch_constants.ml
src/tezos_rpc/tezos_rpc.mli
tests/test_tezos_rpc.ml

To dispatch operations to Tezos, deku need's to estimate a reasonable fee, a requirement to make a good estimate is knowing the constants in Tezos.
This PR implements `Tezos_rpc.Fetch_constants`, allowing us to query all the required data. This is likely the last endpoint required to move away from Taquito.

tezos_rpc: add Fetch_constants

---

README.md
docker-compose.yml
sandbox.sh

We currently create a new flextesa sandbox every time we run `./sandbox.sh setup`. This is unnecessarily slow.
I've added a docker-compose file that creates a flextesa sandbox,
and also brings up a better-call-dev instance available at localhost:8000.
This is really nice for troubleshooting deku - i've been using it for a month or two and just didn't make the PR until now.
So the new workflow is:
- bring up a tezos network once with `docker-compose up -d`.
- Deploy as many deku cluseters as you want with `./sandbox.sh setup`
- If encouter issues with the better-call-dev database (which sometimes happesn when I restart my computer), tear down with `docker-compose down -v` (`-v` is important to stop the network as well).
Closes #422

feat: add docker-compose.yml and improve sandbox

---

README.md
docker-compose.yml
sandbox.sh

`docker-compose` default naming convention isn't use in `sandbox.sh`
```shell script
$ docker-compose up -d
Creating deku_flextesa_1 ... done
Creating deku_postgres_1 ... done
Creating deku_elastic_1 ... done
Creating deku_api_1      ... done
Creating deku_metrics_1  ... done
Creating sandbox-gui   ... done
Creating deku_indexer_1  ... done
```
See the `_1` suffix for every container
While in `sandbox.sh`:
```shell script
docker exec -it deku-flextesa-1 tezos-client "$@"
```
Hence, this leads to:
```shell script
$ ./sandbox.sh
=========== Configuring Tezos client ===========
Error: No such container: deku-flextesa-1
```
Set a `container_name` for every container, with the same naming convention.
- #422 #428

sandbox(fixDockerCompose): add a dedicated name for each container

---

docker/static.Dockerfile
esy.json
sandbox.sh
src/bin/deku_cli.ml
src/bin/dune
start.sh

The name of Deku's CLI is outdated.
This follows the name from `deku-node` and renames `sidecli` to `deku-cli`.

chore: rename sidecli to deku-cli

---

src/tezos_interop/fetch_storage.js
src/tezos_interop/listen_transactions.js
src/tezos_interop/run_entrypoint.js

Currently Deku is loosing Tezos operations in some nodes, leading to nodes not agreeing on what is a valid Tezos operation and stalling the chain.
The issue is only happening on Flextesa, due to the reduced block time and the internal polling rate of Taquito, this PR workaround it by increase the polling rate, in the future we should replace Taquito by Tezos_rpc.

tezos_interop: increase polling rate for Taquito

---

src/bin/deku_cli.ml
src/crypto/random.ml
src/node/flows.ml
src/node/server.ml
tests/test_incremental_patricia.ml
tests/test_ledger.ml
tests/test_runner.ml
tests/test_tezos_interop.ml
tests/test_validators.ml

`reason_to_ocaml.sh` generates `;;` everywhere. But I think that's kind of unidiomatic - it would be better to use `let () = ` in most cases. 
Convert every usage of `;;` to `let () = `

Don't use double semicolon

---

src/bin/deku_cli.ml
src/bin/deku_node.ml

Due to https://github.com/ocaml/ocaml/issues/11090 deku processes are currently named Domain0, breaking commands like `killall`.
This is a workaround until it is fixed on upstream, manually setting the domain name fixes the problem.

chore: OCaml 5 bug changed the process name

---

src/tezos_interop/fetch_storage.js
src/tezos_interop/listen_transactions.js
src/tezos_interop/run_entrypoint.js

The e2e test added in #470 is failing because the confirmation polling is timing out. You can see an example here: https://github.com/marigold-dev/deku/runs/5500148802?check_suite_focus=true#step:8:61
This doesn't happen locally, at least not for me. I think it has to do with the speedo f the machine involved.
Raise the confirmation timeout. I'm not sure if this has any bad effects. If needed, we could make it configurable through an environment variable
that we set in the CI, but I doubt an increase of 6 seconds is going to break us.
- #470

fix: use default confirmation polling timeout

---

src/tezos_interop/scripts.ml
src/tezos_interop/scripts.mli
src/tezos_interop/tezos_interop.ml

Due to a weird interaction between esy and `ppx_blob`, merlin cannot find the needed asset leading to the entire `Tezos_interop` not showing properly on the LSP.
This is more like an workaround, by moving all the blobs to a different module(`Scripts`), now LSP on `Tezos_interop` is working properly.

tezos_interop: move scripts blob to it's own file

---

src/lambda_vm/ast.mli
src/lambda_vm/checks.ml
src/lambda_vm/checks.mli
src/lambda_vm/compiler.ml
src/lambda_vm/compiler.mli
src/lambda_vm/dune
src/lambda_vm/gas.ml
src/lambda_vm/gas.mli
src/lambda_vm/ident.ml
src/lambda_vm/ident.mli
src/lambda_vm/interpreter.ml
src/lambda_vm/interpreter.mli
src/lambda_vm/ir.mli
src/lambda_vm/lambda_vm.ml
src/lambda_vm/lambda_vm.mli
src/lambda_vm/map_with_cardinality.ml
src/lambda_vm/map_with_cardinality.mli

As discussed in the past, Deku needs a VM to execute Ligo smart contracts.
As we're short time on time, unlike what have been discussed in the past, I decided to go with an untyped Lambda VM that can be used to compile both Ligo and OCaml easily. The goal is that in the future this machine could be compiled to a lower level VM.
It provides an strict lambda calculus supporting tail call optimization, combined with int64 primitives, branching using an if C-like and pairs. This allows to describe primitive recursion without stack overflow, pattern matching and complex structures such as tuples, records, natural numbers and etc...
One very important property of this machine is that all the behavior should be defined, including the failure modes, so that in the future when compiling it to …

Implement Lambda VM

---

src/lambda_vm/compiler.ml
src/lambda_vm/dune
src/lambda_vm/ident.ml
src/lambda_vm/ident.mli
src/lambda_vm/interpreter.ml
src/lambda_vm/ir.ml
src/lambda_vm/lambda_vm.ml
src/lambda_vm/lambda_vm.mli
tests/vm/dune
tests/vm/test_errors.ml
tests/vm/test_gas.ml
tests/vm/test_prim.ml
tests/vm/test_recursion.ml
tests/vm/test_simple_expr.ml
tests/vm/test_vm.ml
tests/vm/vm_test.ml

Lambda VM needs proper testing and practical examples of use.
I tested all the base structures of the interpreter and AST, errors and primitive operations. For the basic interpreter features I've just built simple increment/decrement programs. For primitive operations I've built qcheck tests generating int64 for all the operations.
All gas value were adjusted to the bare minimum, so they won't get larger without being noticed.
I've built a few simple programs to test the basic functionality the AST provides, like applications, primitives for arithmetic operations, if expressions, lambdas and manipulating pairs.
Checked for different situations that would happen in real programs, making sure the runtime checks works.
Used QCheck to make property based testing for all available primitive …

Testing for Lambda VM

---

src/node/building_blocks.ml
src/node/flows.ml
src/node/state.ml
src/node/state.mli

Deku or Tezos nodes will not have clocks perfectly in sync, this means that some nodes will receive Tezos operations faster than others, if that happens to be the block producer it will include a Tezos operation not known to the others making this block to be skipped.
The ideal solution would be #481 but that is way more complex to implement, so this PR implements an workaround,. by adding a small delay between receiving a Tezos operation and actually including it on the block.

node: delay before including Tezos operations

---

flake.nix
nix/deku.nix
nix/overlay.nix
nix/shell.nix

Now that we have flakes it would be nice to have a simple way of running our tools with it
Adding the `deku-cli` and `deku-node` as apps.
They can now be run from the repository like `nix run .#deku-cli` or `nix run .#deku-node`.
We should also be able to run `nix run github:marigold-dev/deku#deku-cli` from anywhere.
Checkout branch and run  `nix run .#deku-cli` or `nix run .#deku-node`

Add deku-cli and deku-node as apps in nix

---

.github/workflows/nix.yml

nix code formatting isn't checked.
Check formatting in CI, just like ocaml code.
We may want to use e.g. https://github.com/numtide/treefmt in the future.

chore: add nixfmt ci

---

sandbox.sh

You don't want to run `./sandbox.sh` with old code - you'll inevitably get confused and lose time debugging.
Esy users dodge this because `esy x` rebuilds the environment. Nix users hit this.
I'm not sure if this is a great solution, but it's simple enough. What do you guys think?

add auto-build to ./sandbox.sh

---

docker-compose.yml
prometheus.yml

We'd like to make prometheus stats available to
devs when testing locally.
Add Prometheus server to docker-compse. 
This makes the dashboard available on localhost:9090.
Please test it out! It's super cool :)
Ask Infra, I'm a prometheus noob. But here's a screenshot: 
If you click the "world" button you can select from available metrics. Then click "execute"

feat: add prometheus to docker-compose

---

go_interop/interop.go
tezos-testnet.docker-compose.yml

The two commits in this pull request tackle two issues:
1- Serialization at Set method in interop.go: As mentioned before in Slack, when set is called, "value" is already serialized(type []byte). So Set should expect []byte "value" and should not serialize it again.
2- Port mapping and "host" network_mode in docker-compose for prometheus: 
In recent Docker versions this configuration throws a breaking error: 'docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings'. In older versions port mapping is just ignored if network_mode is "host", so removing port mapping will make it work for new docker versions and it should not break anything in older versions.

Serialization at interop.go and docker error

---

src/bin/deku_cli.ml
src/bin/deku_node.ml
src/bin/files.ml
src/bin/files.mli
src/bin/node_state.ml
src/node/flows.ml
src/node/state.ml
src/node/state.mli
src/tezos_interop/run_entrypoint.js
src/tezos_interop/run_entrypoint.ml
src/tezos_interop/run_entrypoint.mli
src/tezos_interop/tezos_interop.ml
src/tezos_interop/tezos_interop.mli

Due to Multicore not working with `Unix.fork` we had some problems on #414, this happens because spawning processes doesn't work after multiple domains are running.
To work around this problem, this PR makes `run_entrypoint.js` long lived and critical, so if it fails the node also dies with it.
I didn't review this PR, so please be careful. But it seems to work locally

tezos_interop: make run_entrypoint long lived

---

ppx_lambda_vm/ppx_lambda_vm.ml

ppx_lambda_vm doesn't support expressions like `let a = b in c`, which makes some kind of abstractions difficult.
Add support for simple let expressions encoding them as immediate calling lambdas. 
Expressions like `let a = b in c` are encoded like `(fun a -> c) b`.

lambda_vm: support simple let expressions in lambda vm

---

ppx_lambda_vm/ppx_lambda_vm.ml

Using the `land` primitive on ppx_lambda_vm translates to `And` and not `Land` which gives the following error:
```
1 | let _a = [%lambda_vm 0L land 1L]
^^^^
Error: This variant expression is expected to have type prim
There is no constructor And within type prim
```
Use the proper type constructor

Fix the land primitive on ppx_lambda_vm

---

src/bin/deku_cli.ml

`deku-cli` always uses `0` as the nonce for every operation it submits. This makes it impossible to submit the same transaction twice in one block, which is bad because that's sometimes desirable (e.g. for testing). 
Use a random nonce when submitting operations
- Closes #538

Deku-cli: Use random nonce

---

docker/static.Dockerfile

In our docker build `esy install` runs twice and isn't cached properly.
Split the copy commands. Not sure why this fixes it, maybe @ulrikstrid can explain. 
I cherry-picked this commit from #545 because it's super useful by itself.

Fix double esy install

---

src/bin/deku_node.ml
src/bin/node_state.ml
src/node/dune
src/node/flows.ml
src/node/server.ml
src/node/snapshots.ml
src/node/snapshots.mli
src/node/state.ml

Adds full async hashing per #147 . 
In #412, we started storing a list of snapshots. In this PR, we instead store a list of mutable references to `option(snapshot)`'s. 
We hash the protocol's on different threads using `Domainslib.Task.async`,and then updates the references when done.
**This assumes Atomic.t works out of the box with multicore! Is this true?**
Reviewers probably want to check that I'm setting up `Domainslib.Task.setup_pool` correctly. I discovered that unless I call it after `Lwt_main.run`, `Lwt_main.run` fails with:
```
Unix.fork may not be called while other domains were created
```
There is some new complexity in `deku_node.ml`. Specifically, because the `snapshot.current_snapshot` may be `None`, we keep a ref of the last snapshot available, so we can always return a …

Async State Hashing

---

.github/workflows/docker.yml

We can't test a PR in a nice way using docker images.
Our tags are not very descriptive when we just have a long git sha as tag
We add another step that only triggers if a PR has the label "docker" and that will push with a special tag name.
Sets the tag to `YYYY-mm-dd-short_sha` and for the PR it will be prefixed with `pr-`

Improve docker file generation in CI

---

ppx_lambda_vm/ppx_lambda_vm.ml
src/core/contract_vm.ml
src/core/contract_vm.mli
src/core/state.ml
src/lambda_vm/ast.ml
src/lambda_vm/compiler.ml
src/lambda_vm/context.ml
src/lambda_vm/context.mli
src/lambda_vm/interpreter.ml
src/lambda_vm/interpreter.mli
src/lambda_vm/ir.ml
src/lambda_vm/lambda_vm.ml
src/lambda_vm/lambda_vm.mli
tests/vm/dune
tests/vm/test_errors.ml
tests/vm/test_gas.ml
tests/vm/test_io.ml
tests/vm/test_prim.ml
tests/vm/test_recursion.ml
tests/vm/test_simple_expr.ml
tests/vm/test_vm.ml
tests/vm/vm_test.ml

Lambda VM needs a way to access external information that are not the parameters of the smart contract, such as the operation sender or contract address.
Introduce IO primitives for Lambda VM, currently only for sender address.
I also moved gas as well as sender address to a single record named `context`. `sender` should be of `value Lazy.t`, because it needs to be encoded as Lambda VM value, and so it requires to be compiled, which requires gas. So in order to avoid increasing gas cost for contracts that do not use the sender address, this is lazy so it's only compiled after actually been required.

Lambda VM IO primitives

---

README.md
Tiltfile
docker-compose.override.yml
docker-compose.yml
nix/shell.nix
sandbox.sh

Even with `sandbox.sh` the setup still requires some steps, we want to get this down to as few commands as possible.
This PR implements a [Tilt](https://tilt.dev/) setup which allows us to run the network with just 1 command (`tilt up`) and have it automatically rebuild and restart when making changes.
It has 2 dependencies which are the `tilt` command and `docker-compose` because it currently doesn't work with `docker compose`. These are added in the `nix` setup for convenience but needs to be installed by other means if not using `nix`.
Tilt also includes a nice dashboard where you get a overview of what is running and you can do some manual tasks.
Commit f2fd6ea1a2d31a8cd5b24cbc27138e007fce24bc, 28f50a1bd7882b013dc4a495665fc59ba114224c and aafc25b9d507bdee6d97f61a025af6547d066d9e could …

Rework development workflow

---

.github/workflows/e2e_test.yml
docker-compose.yml
nix/shell.nix
sandbox.sh
tests/e2e/asserter.ml
tests/e2e/dune

Deku's tezos integration is easy to break and not notice.
This PR adds a simple e2e smoke test. It does the following:
- runs a deku cluster of 3 nodes for 30 seconds, then kills them.
- checks that a state root hash was published with a block height greater than 20
Control is then passed to a small OCaml program that uses the protocol library to unmarshal each node's `state.bin` and check the following:
- each node's block height is exactly 30 (yes, this is abuses internal knowledge about the block production rate)
- each node's current state root hash is the one posted to Tezos.
These checks are trivial and won't catch any subtle errors in logic, but they're a decent smoke test.
Currently the test needs to be run manually with `./sandbox.sh smoke-test`. I'm talking to infra now about …

Simple end-to-end smoke test

---

tests/vm/test_vm.ml
tests/vm/test_voting_contract.ml
tests/vm/vm_test.ml

We need to make sure that Lambda VM works for more complex contracts, for this we're proposing a voting contract with voting, pausing and resetting capabilities.
Encode the contract with ppx lambda vm and check if the contract produces correct outputs.
The contract also encodes lists and strings as pairs of pairs, using the first element of the pair as the size of the list
in order to have a point of stop when iterating through the list and the second element being the pair of pairs as the contents of the list. The list ends with a `(0L, 0L)` so it doesn't crash from trying to unpair an integer.
Strings are encoded as follows:
```
(<size>, (<first char code>, (<second char code>, (third char code, .... (<last char code, 0L)...)
```
Example: `"Tezos"`
```ocaml
(5L, (84L, (101L, (122L, …
```

Voting contract test for Lambda VM

---

.envrc

I spend a lot of time recursivley rebasing a DAG of branches. This is tedious and error prone. Instead I'm going to try automating this with a tool.
I'm testing gh-stack first. This PR automates some configuration of the tool using our direnv file.
See https://github.com/luqven/gh-stack#usage
direnv ftw
|#559|👉add gh-stack variable|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/559?label=Pending)|-|
|#558|Simplify Sandbox.sh|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/558?label=Pending)|#559|
|#527|Dummy-ticket|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/527?label=Approved)|#558|
|#536|feat: add block-by-level …

[d4hines] add gh-stack variable

---

.github/workflows/nix.yml

CI is failing now with `denied: unauthenticated: User cannot be authenticated with the token provided.`
Add login action in the nix docker workflow
- #556

chore: Add docker login action for nix build

---

.github/workflows/nix.yml

We don't tag the docker images correctly which then fails the push
Add `ghcr.io/marigold-dev/deku:` before the tag name.
Also updated  the PR tag to include the PR number to make it easier to relate them
- #564 
- #556

chore: Fix docker tagging

---

nix/overlay.nix
nix/shell.nix

We want to generate docs for the code we write
Add odoc as a dev dependency in nix so that we can run `dune build @doc`

chore: Add odoc dependency in nix

---

examples/go-counter/README.md
examples/go-counter/main.go
examples/js-counter/example.js
sdks/deku_go_interop/interop.go
sdks/deku_js_interop/package-lock.json
sdks/deku_js_interop/src/interop.ts
src/bin/deku_cli.ml
src/core/state.ml
src/external_vm/external_vm.ml
src/external_vm/external_vm.mli

We don't currently post the transaction hash to the vm. 
Additionally, we have a potential foot gun in that the cli uses an absolute path for the fifo in `/tmp`. I fixed this along the way.
post tx hash.

Add the tx hash 

---

.envrc

When using `direnv` in Nix, it is missing the folder `.direnv` to execute the command.

Nix: add missing folder direnv

---

src/node/server.ml

Four is too small a default for the number of domains to setup.
Let's use 8.

increase number of domains for async state hashing

---

src/node/networking.ml

Currently Deku TPS is quite low, this is due to the block producer waiting the other nodes to parse each block, but currently this is done in serial, which makes so that our pipeline is empty most of the time.
Also we're serializing the same message many times for each validator.
Sends the messages in parallel and serialize only once.

networking: optimize broadcasting

---

src/node/building_blocks.ml
src/node/flows.ml
src/node/state.ml
src/node/state.mli

Currently pending_operations is a list, but in almost all the usages of it we first need to search on it to avoid duplicates, this makes so that any linear operation on pending operations is actually O(n^2).
Because the order doesn't matter for us right now, I changed from a list to a map which in OCaml is a binary search tree, making so that all the O(n^2) operations are now O(n log n).
This code is not ideal, but it's not a big regression, so I would ask for a bit of patience.

node: optimize pending_operations a map

---

flake.lock
flake.nix

NodeJS 12 is now EOL and nix complaints about that when updating.
Just move to NodeJS 14.

deps: move to nodejs 14 as nodejs 12 is EOL

---

flake.lock
flake.nix
nix/deku.nix
nix/npm.nix
nix/patches/remove-webpack-check.patch
nix/shell.nix

The current npm solution for nix doesn't work too well
Use dream2nix that seems to work better with newer versions of npm.
This is a simplified/refactored version of #579
Also removed landmarks on `aarch64-darwin` since it's not compatible with the m1
As you can see here it unblocks m1: https://hydra.strid.ninja/jobset/deku/deku-m1
- #579 This is heavily inspired by the work in this PR so I'm adding co-author

chore: use dream2nix for a better npm experience

---

package-lock.json
package.json
sandbox.sh
src/bin/deku_cli.ml
src/bin/files.ml
src/bin/files.mli
src/bin/node_state.ml
src/helpers/list_ext.ml
src/helpers/list_ext.mli
src/tezos/michelson.ml
src/tezos/michelson.mli
src/tezos_interop/discovery.mligo
src/tezos_interop/tezos_bridge.ml
src/tezos_interop/tezos_bridge.mli
src/tezos_interop/tezos_interop.ml
src/tezos_interop/tezos_interop.mli
src/tezos_interop/tezos_js_bridge.js

Currently, the node assumes there will be a `validators.json` file that provides a mapping from validator keys_hashes to URIs. But when new nodes join the network, or when existing nodes want to change their URI, we need some foolproof way to communicate the new URIs to all the nodes. 
The discovery.mligo contract was written for this purpose, but before this PR it was unused. Its storage is a map from key_hashes to URIs. Anyone can add or update a key_hash and its associated URI (provided they prove they control the key). After the node fetches the list of validator key_hashes from consensus.mligo, it only has to look up those keys in the map maintained by the discovery.mligo contract.
- closes  #160

Fetch validators from discovery.mligo instead of validators.json

---

flake.nix

We don't specify the public keys which means that someone could do a "man in the middle attack" on our cache.
Add `cache.nixos.org` and `deku.cachix.org` public keys

chore: Add trusted public keys for nix cache

---

src/core/contract_ffi.ml
src/core/ledger.ml
src/core/ledger.mli
src/core/state.ml
src/core/ticket_handle.ml
src/core/ticket_handle.mli
src/core/ticket_table.ml
src/core/ticket_table.mli
src/crypto/BLAKE2B.ml
tests/test_ledger.ml

We're going to start moving tickets between implicit and originated accounts  (e.g. putting ticket handles in contract storage, putting them as parameters, dropping from table, etc(as in "End of Thinking Capacity".)
Create a global ticket table, with api that in theory shouldn't allow you to do manipulations with ticket that is already droppped or doesnt belong to you.

add global ticket_table 

---

src/node/snapshots.ml

There's no way to tell when we hashed a new snapshot as of #604
This is a hacky solution - just put it on the `app` log level. A better solution would be to understand how `Logs` actually works, and use Cmdliner to control it. I've started this in #630.

fix: add snapshot logging back

---

dummy_ticket.mligo

There are a few minor issues in dummy_ticket.mligo
- a type alias isn't used once
- some missing whitespace

fix: lint dummy_ticket.mligo

---

.envrc

Our hand-rolled .envrc has relatively poor caching. We can improve it by switching to https://github.com/nix-community/nix-direnv

chore: use nix-direnv instead of hand-rolled .envrc

---

docker-compose.yml

Problem:
Inside the `docker-compose.yml` we are using the "master" tag for baking-bad images which can lead to a non  reproductible dev environment.
The first time I did a `docker compose up`, docker pulled the `master` tag from baking-bad images which was pointing at that time to version 4.2.0 which is not working.
Solution:
Not using the master tag but a fixed version

fix the version of baking bad

---

.github/workflows/nix.yml
.github/workflows/test.yml
README.md
flake.nix

No one on the team is using x86_64-darwin, and
it's slowing down our CI. Let's remove it.

chore: remove x86_64-darwin from CI

---

.github/workflows/nix.yml
.gitignore
Tiltfile
flake.lock
flake.nix
nix/shell.nix
sandbox.sh
tilt/Tiltfile.docker
tilt/Tiltfile.local

`Tilt` currently only runs with nodes in docker, we often want to run them locally
Moved the current (docker based) deku nodes configuration into a separate file.
Created a file for the local workflow with the same API but calls `sandbox.sh` with local settings.
Added a `mode` argument that can be used like `tilt up -- --mode=local`, it will default to `docker` when omitted.
When running in tilt we also override the prometheus service with a special configuration that reads the nodes running in docker.
If `USE_NIX` is unset we will not try to build the docker image with `nix`

chore: Split tilt to allow both docker and local workflow

---

sandbox.sh
src/bin/deku_cli.ml
src/network/network.ml

We want to easily run a test scenario where:
- one start a sandbox
```bash
docker compose up -d
./sandbox setup
```
**Note deku contract address**
- start deku
```bash
./sandbox start
```
- orignate a dummy ticket contract
dummy_ticket.mligo
```mligo
type storage = bytes ticket list
type return = operation list * storage
type vault_ticket = bytes ticket
type vault_deposit = {
ticket: vault_ticket;
address: address
}
type parameter =
| Deposit of {
deku_consensus : address;
deku_recipient : address;
bytes : bytes;
}
| Withdraw of bytes ticket
let main (param, stored_tickets : parameter * storage) : return =
match param with
| Deposit {deku_consensus; deku_recipient; bytes} ->
(match (Tezos.get_entrypoint_opt "%deposit" deku_consensus : vault_deposit contract option)  with 
| Some contract …
```

Add get-balance features to run test scenario

---

nix/shell.nix

Our `PATH` is relative in shell.nix, which breaks things when you're working in deep directories.
Use absolute path.

fix: use absolute path for PATH in shell.nix

---

nix/overlay.nix

Our nix setup isn't working because a commit was removed that was referenced from https://github.com/anmonteiro/nix-overlays. 
@ulrikstrid created a working patch in his fork.

fix: override jsonrpc to a working commit

---

src/core_deku/state.ml
src/core_deku/state.mli
src/protocol/protocol.ml
tests/contracts/test_invocation.ml
tests/contracts/test_origination.ml

Contract origination is using the  hash of the `User_operation`, which is the same for the same `sender * code * storage` triple. The would make possible to overwrite a contract's storage with it's initial value, also making not possible for an implicit account to have multiple contracts with same initial state.
Use the protocol operation hash instead, which depends on stuff like block height and nonce. Also adds an endpoint for making possible to test it.

Fix contract originated address

---

src/bin/deku_node.ml
src/network/network_packet.ml
src/node/state.ml
src/node/state.mli

Successor to #536
There is no way to inspect the contents of blocks from outside a deku node.
Add a `block-by-level` rpc that takes a block level as an int and returns the block with that block height, or `null` if it doesn't know the contents of that block.
This is a workaround to the fact we have no indexer, see #535. But it's pretty essential for using Deku at all, so I think the work-around is justified for now.

feat: block by level RPC

---

src/protocol/block.ml
src/protocol/block.mli

Currently block.payload_hash is not verified when deserializing, which makes Deku susceptible to a couple attacks.
Properly verify it, additionally I also removed the verify function that is not used.

protocol: verify payload hash

---

src/bin/deku_cli.ml
src/node/building_blocks.ml
src/protocol/block.ml
src/protocol/block.mli
src/protocol/protocol.ml

To improve Deku TPS, one trick is to only parse user operations in a block after the block is accepted, but currently all Deku operations are grouped together in the block.operations fields, making so that to access one kind of operation you need to first parse all the other operations.
As consensus_operations and tezos_operations, are both required for the consensus, I split the operations fields in the block, so that in future work we can make `user_operations` opaque and lazy.
This code is not great, but I have plans to refactor it in the following days.

protocol: split operations in a block

---

src/node/building_blocks.ml
src/node/flows.ml
src/node/state.ml
src/node/state.mli
src/protocol/block.ml
src/protocol/block.mli
src/protocol/protocol.ml

Parsing blocks that contain a lot of user operations takes some considerable time, this leads to the block producer waiting the other validators to parse the user operations before they submit the signatures, making a bubble on our pipeline.
As user_operations is not required to sign a block, we make it opaque and only parse it when actually applying a block
This code is not great, it essentially suffers a bit from "prop drilling" but this is so that we avoid parsing the user operations more than once. But I will refactor this in the near future, so please bare with me.

protocol: opaque user operations

---

flake.lock
flake.nix
nix/npm.nix
nix/overlay.nix
nix/shell.nix
sandbox.sh
src/tezos_rpc/http.ml

This PR is a draft because I need feedback regarding Nix.
In his logging PR, @anchpop had to remove annoying debug messages from Piaf, and pin a specific commit of Piaf. His PR got accepted into Piaf so he removed the pin, but we didn't change the version we're using, and the debug messages are back.
Unfortunately, latest versions of Piaf use several dependencies that are not published, so the resulting esy file is a bit of a mess. Also I'm not sure about the state of affairs for Nix, can someone please take a look?
In the long run we should probably stop using Piaf.
(Sidenote: I should have tested logging one last time before merging and I'm sorry I didn't.)
* Update Piaf
* Pin specific versions of `ocaml-sendfile` and `gluten` that are all required by Piaf

Annoying debug messages: upgrading piaf and dependencies

---

nix/shell.nix

We accidentally removed `ocamlformat` from our shell environment
in PR #662, breaking a bunch of stuff.
Add it back. We have to specify that we want 0.20.1 specifically, because nixpkgs has moved on.

fix: add ocamlformat back to shell.nix

---

docker-compose.yml

The Prometheus server is broken when running in local mode
because it is configured to connect with the targets running
on localhost per prometheus.yml. By adding the
"network_mode: host" option to our docker-compose.yml
we can let prometheus talk to the targets in local mode as well as in the
Tilt configuration
Successor to 
- #635

set networking_mode to "host"

---

src/bin/deku_node.ml
src/metrics/blocks.ml
src/metrics/blocks.mli
src/metrics/metrics.ml
src/metrics/networking.ml
src/node/flows.ml

Successor to #537 
We want metrics for block rate and operations per block (from which you can derive operations rate - i.e tps - in prometheus dashboard)
Adds these metrics.
|#691|fix: fix prometheus with tilt|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/691?label=Pending)|-|
|#647|👉feat: block rate and transaction rate metrics  d4hines/block-rate-and-tps|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/647?label=Approved)|#691|
|#658|chore: refactor cli terms                      d4hines/batch-operations|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/658?label=Pending)|#647|
|#681|chore: refactor config out of node …

[d4hines] feat: block rate and transaction rate metrics  d4hines/block-rate-and-tps

---

Tiltfile
docker-compose.yml
src/bin/deku_node.ml
src/metrics/blocks.ml
src/metrics/blocks.mli
src/metrics/metrics.ml
src/metrics/networking.ml
src/node/flows.ml

Fixes Prometheus in docker-compose by removing
the 'ports' setting, which is incompatible with
the host network mode.
Also removes fixes the grouping and removes the
'autoinit=false' config our Tiltfile for several
services. These services are integral to Deku
development, so they should start every time.
|#691|👉fix: fix prometheus with tilt|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/691?label=Pending)|-|
|#647|feat: block rate and transaction rate metrics  d4hines/block-rate-and-tps|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/647?label=Approved)|#691|
|#658|chore: refactor cli terms …

[d4hines] fix: fix prometheus with tilt

---

src/bin/deku_node.ml
src/network/network.ml
src/network/network_packet.ml

We currently don't have any way for users to send batch operations. This kills our TPS, especially since our networking layer is not optimized currently.
Add a `User_operations_gossip` network message (note the plural tense).
|#691|fix: fix prometheus with tilt|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/691?label=Pending)|-|
|#647|feat: block rate and transaction rate metrics  d4hines/block-rate-and-tps|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/647?label=Approved)|#691|
|#658|👉chore: refactor cli terms                      d4hines/batch-operations|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/658?label=Pending)|#647|
|#681|chore: …

[d4hines] feat: batches of operations

---

src/bin/files.mli
src/consensus/apply_block.ml
src/consensus/consensus.ml
src/consensus/consensus.mli
src/consensus/consensus_utils.ml
src/consensus/dispatch.ml
src/consensus/effect.ml
src/consensus/is_signable.ml
src/consensus/is_signable.mli
src/consensus/load_snapshot.ml
src/consensus/steps.ml
src/node/flows.ml

Following #674 we have a quite nicer consensus library, but it doesn't include all operations required by flows.ml.
This PR provides all the tools needed to use the consensus library on Deku.
Mostly handling of operations and validators change was missing. Additionally a lot of small hacks are needed on the current solution so I decided to add even if that makes the consensus library itself a bit worse.

consensus: make the library usable

---

.github/workflows/nix.yml

We run `dune build @runtest` but not `@check` in the CI. This makes it possible
to have code that fails to build and miss it in CI.

chore: check types in ci

---

src/core_deku/ledger.ml
src/core_deku/ledger.mli
src/core_deku/state.ml
src/core_deku/ticket_table.ml
src/core_deku/ticket_table.mli
src/crypto/BLAKE2B.ml
tests/test_ledger.ml

Right now we use a simple Map of {deku_key_hash;ticket_id}  -> Amount.t to store information about ticket ownership on deku. 
In this pr i change the representation of the ledger,  to:
```ocaml 
type t = Amount.t Map.M(Ticket_id).t Map.M(Address).t
```
This will greatly simplify ticket  ownership transfers when you pass them to and from contracts during execution or origination
passing 5 tickets from implicit account into originated contract's storage: 
we only touch the senders submap of tickets when transferring them to the contract/changing the amounts, and this is nice because we don't need to manipulate the whole table at once.
When executing the contract with tickets in it's storage we can just use the submap of said contract from the ticket_table to pass them to ticket_transition …

Change Ticket table representation

---

.github/workflows/nix.yml
Tiltfile

We are usually running tilt in local mode while docker is the default
We are running a bunch of resources that we don't need when just running the CI
Flip the mode configuration to have `local` as default
Add a flag to start all services which defaults to `false`, use it as `tilt up -- --all-services` to start indexer etc

Tilt fixes to make `tilt ci` better

---

.github/workflows/nix.yml

We currently pull the cache multiple times which is kind of slow
Since our e2e tests needs the same thing as our standard (native) build we can run them just after.
Docker needs our static builds so we can do the same here.
#701 should be merged first since it fixes `tilt ci`

chore(ci): Speed up CI by consolidating builds

---

nix/deku.nix
nix/docker.nix

Our docker containers can't talk to other nodes that are using https
Add `cacert` to the correct place.
This PR also moves our dependencies to `buildInputs` and just keeps `cacert` in `propagatedBuildInputs` which makes our closure slightly smaller. Let me know if we want to move this to a separate PR.

Fix TLS in docker

---

nix/deku.nix
nix/overlay.nix
src/bin/deku_sandbox.ml
src/bin/dune

We want to have a more robust and testable sandbox script. 
Rewrite it in ocaml.
There are 8 PRs to do so. Each one of them replace one feature of the sandbox.sh script.
This first PR is just the setup with nix and feather.
| PR           | Description   |
|--------------|------------------|
|  [PR#708](https://github.com/marigold-dev/deku/pull/708)  | sandbox start  |
|  [PR#709](https://github.com/marigold-dev/deku/pull/709)  | sandbox tear-down  |
|  [PR#710](https://github.com/marigold-dev/deku/pull/710)  | sandbox deploy-dummy-ticket/deposit-dummy-ticket  |
|  [PR#711](https://github.com/marigold-dev/deku/pull/711)  | sandbox smoke-test  |
|  [PR#712](https://github.com/marigold-dev/deku/pull/712)  | sandbox deposit-withdraw-test  |
| …

sandbox.sh to ocaml initialization

---

docs/smart-contracts/wasm_contracts/wasm_transfer.wat
sandbox.sh
src/bin/deku_cli.ml
src/core_deku/state.ml
src/core_deku/user_operation.ml
src/core_deku/user_operation.mli
src/smart_contracts/context.ml
src/smart_contracts/context.mli
src/smart_contracts/contract_ffi.ml
src/smart_contracts/contract_ffi.mli
src/smart_contracts/contract_vm.ml
src/smart_contracts/operation.ml
src/smart_contracts/operation.mli
src/smart_contracts/smart_contracts.ml
src/smart_contracts/state.ml
src/smart_contracts/state.mli
src/smart_contracts/ticket_handle.ml
src/smart_contracts/ticket_handle.mli
src/smart_contracts/ticket_transition_table.ml
src/smart_contracts/ticket_transition_table.mli
tests/contracts/test_invocation.ml
tests/contracts/test_origination.ml
tests/e2e/dune
tests/e2e/ticket_handle.ml
tests/e2e/ticket_transfer.ml
tests/wasm/dune
tests/wasm/test_helpers.ml
tests/wasm/test_runtime.ml

We don't update ticket handles in serialized storage when saving new contract state, and that leads to invalid contract state on next execution
Fix it

Wasm-vm fix ticket_handle indexes on reloads

---

sandbox.sh
src/bin/deku_cli.ml
src/bin/deku_node.ml
src/bin/node_state.ml
src/bin/node_state.mli
src/node/building_blocks.ml
src/node/config.ml
src/node/config.mli

Right now, Deku throttles itself to produce blocks every second. Users may want to configure this throttle.
Update:
As @EduardoRFS suggested in #692, this PR additionally implements a short-circuit to the delay if there are any pending operations and changes the default block delay to 5 seconds.
Add an option at the command line to configure the throttle.
|#691|fix: fix prometheus with tilt|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/691?label=Pending)|-|
|#647|feat: block rate and transaction rate metrics  d4hines/block-rate-and-tps|![](https://img.shields.io/github/pulls/detail/state/marigold-dev/deku/647?label=Approved)|#691|
|#658|chore: refactor cli terms …

[d4hines] make minimum block time configurable

---

src/bin/deku_cli.ml

There's some duplicated logic in the CLI - this became apparent as I added a few more commands in deku-p.
Specifically:
1. We want to abstract retrieving the validator URI's out into it's own function.
2. We want to fix how we're defining positional arguments. Currently we define them all over the place, very far removed from where we actually build up the `Term.t` used by Cmdliner.
1. Create a `with_validators` function that accepts a continuation that provides the validator uri's.
2. Turn our positional arguments into functions that accept the position and define the position where they're actually used.
Re: 1. Why not create a function just returns a promise for the validators? Because we want to define some exit behavior if we can't find them, and using a continuation allows us to do …

chore: refactor cli terms

---

sandbox.sh
src/bin/deku_cli.ml

The `deku-cli` can only be used if you have a running Deku cluster on your machine. 
Remove the access to the data folder of each node.
[PR#732](https://github.com/marigold-dev/deku/pull/732)

Use deku-cli without data folder

---

src/wasm-vm/module.ml

Validation errors on smart contracts fail silently, without proper reporting back the related error making debugging smart contracts very difficult. 
Individually report each error with its own error message. For errors related to module validation and syntax error, report the given message with the region of the code that triggered such error.

Improve logging for module validation errors

---

src/bin/deku_node.ml

When the node crashes, it always returns 0 code.
Returns a non zero code in case of an exception

fix: better exit code

---

sandbox.sh
src/bin/deku_bootstrapper.ml
src/bin/deku_node.ml
src/bin/dune
src/consensus/bootstrapper_signal.ml
src/consensus/bootstrapper_signal.mli
src/consensus/consensus.ml
src/consensus/consensus.mli
src/consensus/dispatch.ml
src/consensus/state.ml
src/consensus/steps.ml
src/files/config_files.ml
src/files/config_files.mli
src/files/node_state.ml
src/network/network.ml
src/network/network_packet.ml
src/node/config.ml
src/node/config.mli
src/node/flows.ml
src/node/state.ml
src/protocol/protocol.ml

To start a deku cluster you have to access the data folder of each nodes.
Add a bootstrapper message in the consensus steps to start the cluster.

Cluster bootstrapper

---

dummy_ticket.mligo
src/core_deku/state.ml
src/core_deku/tezos_operation.ml
src/core_deku/tezos_operation.mli
src/tezos_interop/consensus.mligo
src/tezos_interop/tezos_interop.ml
src/tezos_interop/tezos_interop.mli
tests/contracts/helpers_contracts.ml

As mentioned in https://github.com/marigold-dev/deku/issues/773 the types used in the current contracts (consensus + dummy_ticket) allow to deposit tickets to an originated account ("KT1 address"). Moreover, in various files, types allow all Tezos addresses as targets to a deposit, leading to the use of `failwith`.
```bash
bad_address="KT1NHBasfrhX9d2SgGVARd3Y1C5nkhfoEks3"
tezos-client transfer 0 from alice to $dummy_ticket --entrypoint mint_to_deku --arg "(Pair (Pair \"$deku_consensus\" \"$bad_address\") (Pair 100 0x))" --burn-cap 0.05
```
1. Change the two aforementioned contracts to prevent this
2. Modify `tezos_interop` to use a Key_hash.t instead of an Address.t and remove everything that's now redundant
I tested deposit and withdrawal manually. I _did not_ test TzPortal against …

Use key_hash instead of address in contracts + deku

---

src/bin/deku_node.ml

> Cross-Origin Resource Sharing ([CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS)) is an [HTTP](https://developer.mozilla.org/en-US/docs/Glossary/HTTP)-header based mechanism that allows a server to indicate any [origins](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (domain, scheme, or port) other than its own from which a browser should permit loading resources. CORS also relies on a mechanism by which browsers make a "preflight" request to the server hosting the cross-origin resource, in order to check that the server will permit the actual request. In that preflight, the browser sends headers that indicate the HTTP method and headers that will be used in the actual request.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS](https://developer.mozilla.org/ …

fix: allow HTTP CORS

---

check.sh
reset.sh
src/bin/node/deku_api.ml
src/bin/node/deku_node.ml
src/bin/node/node.ml
src/bin/node/node.mli
start.sh

Sends blocks through websocket so that clients will be able to observe the chain and check if their operations are included in the chain without pulling the api

feat/deku-api: send blocks through websockets

---

src/crypto/BLAKE2b.ml

```
Failure("cannot deserialize \"2b97aeab16c6ce67abd1fbc66782540a7a6f584800d44da84e2afa316747c7ff\" to blake2b")
```
Create a proper string instead of json formatted string

To string instead of json string

---

client/examples/nodejs/index.ts
client/examples/nodejs/package-lock.json
client/examples/nodejs/package.json
client/src/index.ts
client/src/network/index.ts

Fixes (one of) Gauthier's bugs:
```
DekuToolkit({
dekuRpc: "https://deku-canonical-vm0.deku-v1.marigold.dev/"
```
was making the library fail.

fix: support slash at the end of urls

---

client/package-lock.json
client/package.json

0.1.7 does not work with nodejs because it was publish with `npm run dev` command, I publish 0.1.8 with `npm run build` now.

Deku toolkit@0.1.8

---

deku-p/src/indexer/dune
deku-p/src/indexer/types.ml
nix/deku-p/deku.nix

Indexing all the blocks takes a lot of place on the disk
Compressing the blocks with gzip before saving them. 
Using gzip algorithm slow down the block insertion in sqlite
Here is some data that show the time to insert a block in sqlite
With gzip:
- average: 0.048s
- 95 percentile: 0.054s
- 99 percentile: 0.069
Without gzip:
- average: 0.035
- 95 percentile: 0.038
- 99 percentile: 0.039
But the size gain is considerable:
- 1k blocks of 10 mb with gzip: 45mb
- 1k blocks of 10 mb without gzip: 9.8gb
The gain of size is significant

bug/indexer: compress blocks with gzip

---

deku-p/deku-toolkit/examples/react/package.json
deku-p/deku-toolkit/examples/react/src/App.tsx
deku-p/deku-toolkit/package.json
deku-p/deku-toolkit/src/index.ts
deku-p/deku-toolkit/src/network/index.ts

Get VM state was missing in Deku Toolkit.
This PR aims to add it.
- new function available in deku-toolkit to fetch VM State
- example of the previous point in the `react-app`
- use local deku-toolkit in the react example
- changed version of deku-toolkit to 0.1.9 (not published)

[deku-toolkit] add vmState endpoint and example

---

deku-p/src/core/bin/api/api_error.ml
deku-p/src/core/bin/api/api_error.mli
deku-p/src/core/bin/api/deku_api.ml
deku-p/src/core/bin/api/handlers.ml

It's impossible to know if an operation has been included. Except by pulling each second the state
Add a way to get the receipt of an operation

feat: endpoint to query operation receipt

---

deku-p/src/core/bin/api/deku_api.ml
deku-p/src/core/bin/api/handlers.ml
deku-p/src/core/ledger/contract_address.ml

Origination of a contract on deku only gives us a operation hash
Add an helper in the api to compute the contract address

feat: endpoint to get the contract hash

---

deku-p/src/core/crypto/tests/alg_intf_tests.ml
deku-p/src/core/crypto/tests/data_for_tests/data_gen.txt
deku-p/src/core/crypto/tests/deku_crypto_tests.ml
deku-p/src/core/crypto/tests/test_ed25519.ml
deku-p/src/core/crypto/tests/tezos_test_data.ml

We want to prevent regressions in the Deku_crypto library
This PR sets up all the infrastructure for running tests on `Alg_intf.S` and provides a single example test.
This is the head of a chain which will incorporate regression tests for `Alg_intf.S`.

Initial crypto tests 

---

start.sh

Example of output:
```
2: deku-node: [INFO] Applying level 12 at time 1667048982.611
[2022-10-29T13:09:42Z INFO  vm_library::run_loop] Received Noop transaction
[2022-10-29T13:09:42Z INFO  vm_library::run_loop] Received Noop transaction
2: deku-node: [INFO] Producing Block [hash: Db2hLgTeSGZLFiCvPrTZW4ogX4a3VUY3tNGMRjYPyP89TJCoT6eV, level: 13]
2: deku-node: [INFO] Incoming block Block [hash: Db2hLgTeSGZLFiCvPrTZW4ogX4a3VUY3tNGMRjYPyP89TJCoT6eV, level: 13]
0: deku-node: [INFO] Incoming block Block [hash: Db2hLgTeSGZLFiCvPrTZW4ogX4a3VUY3tNGMRjYPyP89TJCoT6eV, level: 13]
3: deku-node: [INFO] Incoming block Block [hash: Db2hLgTeSGZLFiCvPrTZW4ogX4a3VUY3tNGMRjYPyP89TJCoT6eV, level: 13]
1: deku-node: [INFO] Incoming block Block [hash: Db2hLgTeSGZLFiCvPrTZW4ogX4a3VUY3tNGMRjYPyP89TJCoT6eV, level: …
```

Printing nodes in start.sh

---

deku-p/src/core/bin/node/deku_node.ml
deku-p/src/core/bin/node/node.ml
deku-p/src/core/chain/chain.ml
deku-p/src/core/consensus/consensus.ml
deku-p/src/core/constants/deku_constants.ml
deku-p/src/core/external_vm/external_process.ml
deku-p/src/core/gossip/gossip.ml
deku-p/src/core/gossip/message_pool.ml
deku-p/src/core/network/network_manager.ml
deku-p/src/core/tezos_interop/js_process.ml
deku-p/src/core/tezos_interop/tezos_bridge.ml

Newlines in logs were introduced by https://github.com/marigold-dev/deku/commit/de6c7ec6acc00def73ee7ede7e7a3b816e74b6dc - sorry about that
The second commits fixes a production bug which goes like this:
- node 3 fails for some reason, say at level 205185
- the other nodes continue
- when node 3 gets back online, the other nodes reached level 205211, but every block below 205200 was dropped
- node 3 starts receiving and accumulating blocks > 205201, doesn't apply any of them, fills its RAM and dies.
Example of output (before fix) with a cycle of 30 instead of 600:
```
3: deku-node: [INFO] Chain started at level: 40
3: deku-node: [INFO] Incoming block Block [hash:
Db2n1fvMKHCUifW6ggPG4oucDjSsJFg9bEXFSmpZFVLzWTX1Vsgi, level: 61]
3: deku-node: [INFO] accepted: 61
3: deku-node: [INFO] …
```

Fixes newlines in logs and cycles drops

---

deku-p/deku-toolkit/package.json

@tzstamp/helpers is a dependency. 
Not a dev dependency.

fix toolkit dependencies

---

deku-c/deku-c-toolkit/package.json
deku-c/deku-c-toolkit/src/contract.ts
website/package.json

- The deku-c-toolkit can not parse several types: Union, List, Unit 
- Bug in the Pair parsing
- Implements parsing for missing types
- Fix the pair parsing bug
A new version has been set: 0.1.3
The website was updated to this version.

Fix toolkit parsing

---

deku-p/src/core/bin/benchmark/deku_benchmark.ml

We want to have easy access to benchmarks, and also be able to easily export them to csv for use in the dashboard
This PR parameterizes all benchmarks to use a common module interface while preserving original functionality.

Prepare benchmarks for cli usage

---

deku-p/src/core/bin/api/deku_api.ml
deku-p/src/core/bin/node/deku_node.ml
deku-p/src/core/block_storage/block_storage.ml
deku-p/src/core/block_storage/block_storage.mli
deku-p/src/core/stdlib/parallel.ml
deku-p/src/core/stdlib/parallel.mli

Loading and storing blocks is not fast and this currently happens on the main thread, drastically slowing the chain.
Move all the storage work load to a specific worker.

storage: move computing to worker

---

deku-c/deku-c-toolkit/package.json
deku-c/deku-c-toolkit/src/contract.ts
website/package.json

The deku-c-toolkit can't parse the option type from the wasm contract storage
Improve the parser of the deku-c-toolkit

fix/deku-c-toolkit: option parsing wasm 

---

deku-p/src/core/tezos_interop/tezos_bridge.ml
deku-p/src/core/tezos_interop/tezos_bridge.mli
deku-p/src/core/tezos_interop/tezos_interop.ml
deku-p/src/core/tezos_interop/tezos_js_bridge.js

- Wrong level of error from the js interop
- Errors from the interop are not explicit
- Parsing the errors that come from the interop and apply a good log level on them
Is a screen of the new log in case a operation can't be submitted due to an insufficient balance:

JS Interop: better error management and logging

---

deku-c/tunac/lib/compiler.ml
deku-c/tunac/lib/template.ml

`PUSH bool True` and `PUSH bool False`  doesn't work. Also the `$now` import was previously removed.
They needed to be implemented, also put `$now` back.

Fix push bool primitives and NOW

---

deku-p/src/core/bin/node/node.ml

When a node join the network for the first time it sends a request for blocks above the level 0. But the level 0 is not stored in the Block_storage. 
As soon as a block is not found the node does no more answer the request. 
When a node receive a request for a block n, it does not look for the block n but starts returning the block n+1

node: fix off-by-one when sending blocks

---

deku-p/src/core/bin/benchmark/deku_benchmark.ml

We want to know how many domains we're using in the deku-benchmark
Add a printf that tells us so

added eprintf for domains

---

deku-c/python-client/.gitignore
deku-c/python-client/README.md
deku-c/python-client/deku/core/address.py
deku-c/python-client/deku/core/operation.py
deku-c/python-client/deku/core/proof.py
deku-c/python-client/deku/core/ticket.py
deku-c/python-client/deku/deku.py
deku-c/python-client/deku/network/http.py
deku-c/python-client/deku/tezos_contracts.py
deku-c/python-client/deku/utils.py
deku-c/python-client/dev-requirements.txt
deku-c/python-client/examples/bridge.py
deku-c/python-client/examples/contracts.py
deku-c/python-client/requirements.txt
deku-c/python-client/setup.py
docs/Deku-Canonical/deku_c_python.md

Edit: I completely failed to install the necessary requirements with nix.
I think this is mergeable as such because I would use it in other projects (before making PRs to improve it). It still lacks
- tests
- proper MyPy setup
- strengthening against errors in http.py
- contract state
- support for Ligo and (non-Michelson) WASM
- ~~doc~~ docstrings
- ~~black setup~~
`examples/` both work in a fresh environment, when targeting Canonical (the default). I don't expect it to work with `main` though, but I believe we have the same issue with the JS library?

feat: python client library
