fa12_ticket_wrapper.religo
I have no idea how to test the contract, but it typechecks. We need to add tests to make sure it works. This is also my first smart contract so there may be issues with it.
=> Add contract that wraps FA1.2 tokens in tickets

bin/genesis_helper.re
The `genesis_helper.exe make-credentials` script did not generate credentials in the way other tools expected. We now expect folders representing each validator, containing an identity and a list of other validators. This MR changes `genesis_helper.exe make-credentials` to follow this format. 
New folder structure:
=> Fix the credential maker so it's aligned with what the other scripts expect

protocol/ledger.re, protocol/ledger.rei, protocol/protocol.re, tests/test_ledger.re, tests/test_protocol.re
The current ledger is not well tested and provides the concept of a frozen ledger which is not useful as of #35 
- Remove frozen portion of the ledger
- Clean API to reflect that
- Add unit tests for the full API
Commit-to-commit should be quite straightforward here
- #34
=> Refactor Ledger API

esy.lock/index.json, esy.lock/opam/bigstringaf.0.8.0/opam, esy.lock/opam/conf-libssl.3/opam, esy.lock/opam/conf-pkg-config.2/opam, esy.lock/opam/dune-build-info.2.9.0/opam, esy.lock/opam/dune-configurator.2.9.0/opam, esy.lock/opam/dune.2.9.0/opam, esy.lock/opam/faraday-lwt-unix.0.8.1/opam, esy.lock/opam/faraday-lwt.0.8.1/opam, esy.lock/opam/faraday.0.8.1/opam, esy.lock/opam/magic-mime.1.2.0/opam, esy.lock/opam/ocaml-lsp-server.1.7.0/opam, esy.lock/opam/ocaml-migrate-parsetree.2.2.0/opam, esy.lock/opam/parsexp.v0.14.1/opam, esy.lock/opam/ppxlib.0.22.2/opam, package.json
Bumps the OCaml version to the latest multicore master,sadly it means rebuilding everything.
=> chore: bump dependencies

tests/test_validators.re
Adds two additional test cases for the Validators module and some comments.
=> improve validators module tests

tezos_interop/consensus.mligo
When doing #77 we need to organize internally the contract, but modules in Ligo generate huge performance overhead.
For now I'm proposing just namespacing each step of the contract, the consensus one which is responsible for handling the `root_hash` is the current consensus contract.
- #34
=> put namespaces in consensus contract

tezos_interop/consensus.mligo
As per #34 we need to be able to move tickets to the sidechain.
Add a deposit entrypoint on the contract, this should be detected by the node and calls `Ledger.deposit` when the operation is added to a block.
- #34
=> add deposit on consensus

protocol/ledger.re, protocol/ledger.rei, tests/test_ledger.re
With #88 the consensus contract allow the user to provide a proof that he burned the money on the sidechain, but currently the patricia tree is not integrated in the sidechain itself.
This doesn't solve the problem entirely, but it creates the needed infrastructure from the ledger to integrate the patricia tree in the future on the protocol.
- #34 
- #88
=> add withdraw handles on ledger

bin/sidecli.re
To `setup-node` you need to have a consensus contract address, but to setup the consensus address you need an identity which is provided by `setup-node`.
This PR is a first step in separating `setup-node` to avoid problems the one above. It is based on the work at #111 by @callistonianembrace 
- #111
=> add setup-identity command

bin/sidecli.re
`inject-genesis` was a command added to use during development but it's not required anymore and it should not be exposed to users.
As `produce-block` and `sign-block` replaces it and are production ready, this removes `inject-genesis`.
This breaks the tmuxinator script. So I opened a follow up issue #126
- #126
=> remove unused inject-genesis

bin/sidecli.re
`make-credentials` was a command added to use during development but it's not required anymore and it should not be exposed to users. Similar to #127
As `setup-node` and `setup-identity` replaces it and are production ready, this removes `make-credentials`.
This breaks the tmuxinator script. So I opened a follow up issue #126
- #126
=> remove unused make-credentials

setup.sh
Users of the docker client like me would have found it difficult to use the previous script as-is.
Also, the script used the account alias `alice` every time, which made it fail for repeat runs. (Also 'alice' is not a very informative name.)
Also, if you want to use a mockup client to avoid the hassle of running a full node, that was difficult in the previous version, but I added some instructions for how to do that.
Fix all these things in one monster PR. My justification is that I'm not making a PR to merge into main so I don't need to make it good.
=> Setup.sh: Add instructions for using mockup client

bin/http_server.re, node/flows.re
We need to detect deposit operations that happened on Tezos, on #133 the machinery required was added but it's not integrated on the sidechain node.
This adds a flow for main chain operations and integrate it on http_server, which makes so that main chain operations are properly added to `pending_main_ops`.
- Closes #34 
- Closes #61
=> Integrate node main chain operations

bin/http_server.re, node/networking.re
This endpoint was designed as a temporary solution and it's not needed anymore.
Remove it.
=> remove unused endpoint /data-to-smart-contract

bin/sidecli.re
Currently `produce-block` requires a `wallet.json` which should not be required to run a node, but `produce-block` is required to run a node.
We can use the identity file from the node to get the needed data and also the `state.bin` to produce the block.
=> expect only folder on produce-block

protocol/wallet.re
Currently both the private key and public key are using Tezos like addresses, but wallet is still using hex.
Use `tz1` for wallets.
=> use tz1 serialization for wallet(address)

bin/sidecli.re
Currently the validator list on the sidecli are loaded from a hardcoded path, this means that if the files are in a different folder everything stops working.
Always receives a node folder as input and read the `validators.json` from this folder, in practice this means that now `create-transaction` also has an additional folder_node  argument.
=> always use validators from a node

bin/sidecli.re
At #152 create-transaction was broken because I forgot to update the number of arguments.
Fix the number of arguments.
=> fix create-transactions arguments

.gitignore
**Problem**
*.bundle.LICENSE.txt files keep showing up as untracked files in the VCS
**Solution**
This PR adds them to .gitignore
=> Adds *.bundle.js.LICENSE.txt to .gitignore

.github/workflows/test.yml
Github actions workflow, test.yml, doesn't have an appropriate name.
This PR changes the name from 'Hello Reason' to 'Deku Test Workflow'.
=> Fixes GH workflow's name

bin/sidecli.re
Missing CLI for a node operator to add or remove trusted validators from node's state
This PR uses endpoint from #185 to provide a convenient CLI
=> CLI: Add/Remove trusted validators from a node's local state

node/building_blocks.re, node/flows.re, node/state.re, node/state.rei, protocol/operation.re, protocol/operation.rei, protocol/protocol.re, protocol/state.re
Adding/removing validators is missing right now
This PR adds protocol level support for submit addition and removal of validators
=> Proto: Adds support for add/remove validators in the sidechain

bin/sidecli.re
The sidecli code is duplicating the JSON file names in many places, this is problematic as there is no source of truth for it.
This is not a proper solution but just an improvement, by making so that those file names appear only once and centralized on the sidecli.re file.
=> remove duplicated file names on sidecli

deku/.vscode/settings.json, ligolang/.vscode/settings.json, zinc/.vscode/settings.json
Custom configuration was required to get vscode IDE features working with ocaml platform
Add that configuration to .vscode/settings.json folders.
=> Smart contracts: add .vscode settings.jsons

deku/.vscode/settings.json, ligolang/.vscode/settings.json, zinc/.vscode/settings.json
I kept accidentally switching my line endings to crlf
Add setting to vscode.json to prevent making that mistake
=> Set line ending in settings.json

ligolang/src/passes/13deku-zincing/compiler.ml, ligolang/src/test/zinc_test.ml, zinc/lib/Zinc_interpreter.ml, zinc/lib/Zinc_types.ml
Lists are currently unsupported in zinc
Add lists to zinc
- #163
=> Add lists to zinc

crypto/base58.ml, crypto/base58.mli, crypto/crypto.re, crypto/crypto.rei, crypto/key.re, crypto/key.rei, crypto/key_hash.re, crypto/key_hash.rei, crypto/p256.re, crypto/p256.rei, crypto/secret.re, crypto/secret.rei, crypto/signature.re, crypto/signature.rei, protocol/wallet.re, tests/test_tezos_interop.re
We don't have support for tz3 addresses in Crypto library right now, but we need it for tezos_interop
This PR adds tz3 support to Crypto library
=> PROTO: Tz3 interop

.github/workflows/docker.yml, docker/alpine.Dockerfile
We want the docker image to be built automatically
Adds github actions and pushes to the github registry (for now, we can add Docker hub later)
- #337
=> Add GitHub Actions for Docker

ligolang/src/test/contracts/super_simple_contract.religo, ligolang/src/test/zinc_tests.ml
We need to convert zinc programs to json, but this is untested
Test it
=> Add json test

ligolang/.ocamlformat-enable, ligolang/src/passes/13deku-zincing/compiler.ml, ligolang/src/test/contracts/if_then_else.religo, ligolang/src/test/contracts/if_then_else_op.ligo, ligolang/src/test/contracts/if_then_else_op_function.ligo, ligolang/src/test/zinc_tests.ml, zinc/lib/zinc_interpreter/Zinc_interpreter.ml
See the third issue described in #358
Properly tail-compile matching on records
=> Ligo: Tail compile match on record

bin/sidecli.re, core/amount.re, core/amount.rei, core/dune, node/flows.re, node/networking.re, protocol/dune, protocol/ledger.re, protocol/ledger.rei, protocol/operation.re, protocol/operation.rei, protocol/protocol.re, tests/test_ledger.re, tests/test_protocol.re
As discussed in the past we need a way to separate the core state machine from the protocol / consensus.
This PR is the first step in this direction by introducing the core library and moving the Amount module to it. Also using Core.Amount module everywhere.
=> core: Amount

core/ledger.re, core/ledger.rei, protocol/dune, protocol/protocol.re, protocol/protocol_state.re, protocol/validators.re, protocol/validators.rei, tests/test_ledger.re
Same as #390.
As Ledger is an API that was reworked it's not that bad. So mostly move it to Core.
- #390
=> core: Ledger

core/state.re, core/state.rei, core/tezos_operation.re, core/tezos_operation.rei, core/user_operation.re, core/user_operation.rei
Same as #390, additionally our current state machine is very badly defined in the Protocol, mixing things like User_operations, Tezos_operations and Consensus_operations.
Here I re-implement the core state machine, defining it's operations and state transition functions, this should in the future be consumed by the Protocol.
- #390
=> core: User_operation, Tezos_operation, State

docker/static.Dockerfile
The source path has been changed, and the reference to it has not changed in the dockerfile.
Change the path used in the dockerfile.
- #423
=> Fix docker CI

tests/.ocamlformat, tests/dune, tests/test_tezos_rpc.ml
Currently Tezos_rpc has no tests as we don't have the testing infrastructure required.
This PR doesn't really solve the problem, but it helps by adding some manual tests.
=> tests: manual tests for Tezos_rpc

src/crypto/base58.ml, src/crypto/base58.mli, src/crypto/crypto_intf.mli, src/crypto/ed25519.ml, src/crypto/encoding_helpers.ml, src/crypto/encoding_helpers.mli, src/crypto/p256.ml, src/crypto/secp256k1.ml, src/crypto/signature.ml, src/crypto/signature.mli, src/tezos/operation.ml, src/tezos/operation.mli, src/tezos/protocol_hash.ml, src/tezos/protocol_hash.mli, src/tezos/tezos.ml, src/tezos/tezos.mli, src/tezos_rpc/fetch_block_operations.ml, src/tezos_rpc/fetch_block_operations.mli, src/tezos_rpc/http.ml, src/tezos_rpc/http.mli, src/tezos_rpc/operation_content_with_result.ml, src/tezos_rpc/operation_content_with_result.mli, src/tezos_rpc/preapply_operations.ml, src/tezos_rpc/preapply_operations.mli, src/tezos_rpc/tezos_rpc.mli
In the mission of removing Taquito, we need to be able to estimate the gas cost of an operation and to actually simulate it before injecting.
This PR is also a non ideal implementation it just hacks together an integration with /preapply
=> tezos_rpc: add Preapply_operations

.github/workflows/e2e_test.yml, e2e_smoke_test.sh, sandbox.sh
We need a GitHub action for e2e tests.
A GitHub action that uses flextesa node and Marigold testnet node to validate.
- #470
=> add e2e actions

esy.json
Need access to core_bench to proceed with benchmarking the VM. 
Built core_bench separately and referenced in esy.json
=> benchmarking: added core_bench to esy.json

esy.json
=> Revert "benchmarking: added core_bench to esy.json"

.envrc, .github/workflows/nix.yml, .gitignore, .ocamlformat, README.md, flake.lock, flake.nix, nix/deku.nix, nix/overlay.nix, nix/shell.nix, package-lock.json, package.json, sandbox.sh, src/tezos_interop/webpack.config.js
Successor to #438. @ulrikstrid did most of the heavy lifting, but in this PR I've cleaned the git history and polished things.
=> Pure Nix setup, take 2

src/bin/node_state.ml
We currently hard-code the URI's of each validator to be `http://localhost:444${i}` where `i` is the index of the validator in consensus contract storage. Besides being inflexible, this prevents any testnet distributed across multiple machines.
Lookup the URI's from validators.json. This is not ideal, but strictly more flexible than our current
model.
This method of looking up the URI's shoudl be replaced by #450 as soon as its ready.
=> Read uri's from validators.json

.dockerignore, .github/workflows/docker.yml, docker/esy.Dockerfile
The current docker setup is broken for some reason and we want 
Since there's a demo coming up we just want some docker setup to work for the testnet, this is a workaround that just uses `esy x ...` at runtime to get things going. Should be good enough until we can fix the static image.
=> Add Dockerfile using esy at runtime

src/bin/deku_cli.ml, src/core/contract_vm.ml, src/core/contract_vm.mli, src/core/state.ml, src/core/user_operation.ml, src/core/user_operation.mli, tests/contracts/test_contracts.ml, tests/contracts/test_invocation.ml
We need to have a way to invoke a contract
add a user operation to invoke a contract and expose cli interface to it using already existing `transfer` command
=> Smart contracts: Contract invocation

.github/workflows/nix.yml, nix/shell.nix, reason-to-ocaml.sh, sandbox.sh
Bash is really really hard.
Add the https://www.shellcheck.net/ linter to our code and CI
Currently I only add it to the nix setup. We can defer merging this until everyone is on Nix if we want.
Closes #548
=> chore: add shellcheck linting

src/bin/deku_cli.ml, src/core/contract_vm.ml, src/core/contract_vm.mli, src/core/state.ml, tests/contracts/dune, tests/contracts/test_invocation.ml, tests/contracts/test_origination.ml
We need to support multiple vm's, so this is mainly a pr about having interface to multiple vms
Add a dummy vm
=> Add dummy vm

.github/workflows/nix.yml, flake.nix, nix/deku.nix, nix/docker.nix, nix/overlay.nix
If we are to move to nix we need to build images with nix as well
Build docker images with nix, we also add static builds because we want to use them in docker
- #555
=> chore: Build docker images with nix

examples/go-counter/README.md, examples/go-counter/main.go, examples/js-counter/example.js, sdks/deku_go_interop/interop.go, sdks/deku_js_interop/package-lock.json, sdks/deku_js_interop/src/interop.ts, src/bin/deku_cli.ml, src/core/state.ml, src/external_vm/external_vm.ml, src/external_vm/external_vm.mli
=> Add the tx hash  (#588)

src/node/flows.ml
=> fix: check signature exists in validator list

.github/workflows/nix.yml
We can't be sure our nix setup works on macOS as we do with esy
Run the nix build on both Linux and macOS
=> Run nix CI on macOS

flake.lock, flake.nix, nix/deku.nix
We want to use pollinate
Add pollinate's overlay from https://github.com/marigold-dev/pollinate/pull/41
When the above PR is merged we can change the flake input to point to main instead of my branch
=> fix nix pollinate

src/bin/deku_cli.ml
We dont print out originated contract address and use incorrect positional argument
Do it
=> fix origination of smart_contracts

flake.nix, nix/deku.nix
Sometimes we have rebuilds in nix even when we changed a file that we don't care about
Since we added  `nix-filter` in a previous PR we can use that since it seems to work very well for this
- #612
=> chore: Use nix-filter to filter sources

esy.json, esy.lock/index.json, esy.lock/opam/benchmark.1.6/opam, esy.lock/opam/landmarks.1.4/opam, esy.lock/opam/memtrace.0.2.2/opam
Add libs for benchmarks in Esy.
=> Esy: add libs: memtrace, benchmarks and landmark in esy

esy.json, esy.lock/index.json, esy.lock/opam/tezos-error-monad.12.3/opam, esy.lock/opam/tezos-lwt-result-stdlib.12.3/files/tests_in-packages.patch, esy.lock/opam/tezos-lwt-result-stdlib.12.3/opam, esy.lock/opam/tezos-micheline.12.3/opam, esy.lock/opam/tezos-stdlib.12.3/opam, esy.lock/opam/zarith_stubs_js.v0.15.0/opam, src/tezos/michelson_v1_primitives.ml
We've fallen a bit behind tezos mainline repo wrt michelson_v1_primitives
update the file and dependency for tezos_micheline
=> chore: Update michelson_v1_primitives.ml and tezos_micheline

sandbox.sh, tilt/Tiltfile.docker
We have an off-by-1 that causes us to launch n+1 nodes.
Fix it.
=> Fix number of nodes launched by sandbox.sh

tests/contracts/helpers_contracts.ml, tests/contracts/test_invocation.ml, tests/contracts/test_origination.ml
The code in the `tests/contracts` are duplicated.
=> Optimise duplicated code

src/wasm-vm/extern.ml, src/wasm-vm/memory.ml, src/wasm-vm/runtime.ml, src/wasm-vm/value.ml, src/wasm-vm/wasm_vm.ml, src/wasm-vm/wasm_vm.mli, tests/wasm/hexdump.ml, tests/wasm/test_runtime.ml
A contract needs way to interact with the outside world, including IO and possibly hashing functions.
Make possible to add imports to WASM contracts providing translation between types and ways to manipulating memory from these foreign functions
**Note**: Read https://github.com/marigold-dev/deku/commit/4f4d23010e3d0f9a58c211cec1d3700f50045d56 first and #618 for the previous commit.
=> Wasm VM external interface

src/bin/deku_cli.ml, src/core_deku/contract_vm.ml, src/core_deku/contract_vm.mli, src/core_deku/dune
We need to run WASM contracts on Deku
Integrate wasm_vm into Deku core and CLI.
=> Wasm vm integration

benchmarks/state_hash/bench_state_hash.ml, benchmarks/state_hash/dune, benchmarks/state_hash/map_hash.ml, benchmarks/state_hash/maps.ml
Right now our state hashing uses yojson, and we didn't have a benchmark to see how fast this was, or compare it to other options.
This PR builds a pseudo state and compares the hashing time of using yojson and bin_prot
=> State hash benchmarking

docs/smart-contracts/wasm_contracts/wasm_mint.wat, src/bin/deku_cli.ml, src/core_deku/contracts.ml, src/core_deku/ledger.ml, src/core_deku/ledger.mli, src/core_deku/state.ml, src/core_deku/ticket_id.ml, src/core_deku/ticket_id.mli, src/smart_contracts/context.ml, src/smart_contracts/context.mli, src/smart_contracts/contract_ffi.ml, src/smart_contracts/contract_vm.ml, src/smart_contracts/conversions.ml, src/smart_contracts/conversions.mli, src/smart_contracts/operation.mli, src/smart_contracts/ticket_handle.mli, src/smart_contracts/ticket_transition_table.ml, src/smart_contracts/ticket_transition_table.mli, tests/contracts/helpers_contracts.ml, tests/e2e/asserter_balance.ml, tests/e2e/asserter_contract.ml, tests/test_ledger.ml, tests/wasm/test_helpers.ml
Contracts should be able to create tokens so then can have their own economics
Add the support for tickets inside WASM VM contracts
=> Mint tickets from contracts

docker-compose.yml, package-lock.json, package.json, src/bin/deku_cli.ml
We want to test deku against jakartanet
Update  flextesa and run `jakartabox`
=> Update to jakartanet

sandbox.sh, tests/e2e/0001-wip-disable-user-operation-broadcast.patch, tests/e2e/dune, tests/e2e/load_test.ml
We want a reproducible way of testing through the throughput of Deku. This will help us determine where our bottlenecks are and where to focus optimization effrots.
This PR adds an e2e test similar to that in #470 that attempts to saturate the network with ticket transfer transactions. 
There is a lot that could be improved in this PR:
- I have not tested the efficiency of the load tester. Obviously, if your load tester is not fast enough, you won't fully exercise your system. So I can't say with confidence that this truly saturates the network.
- We obviously need to add more variety to the tests and the testing conditions (different network topologies, killing nodes etc.).
- I'd like to automate the execution and reporting of these benchmarks but I need help from infra to do that (cc …
=> [d4hines] Benchmarking: ticket transfers                 d4hines/ticket-transfer-benchmarking

src/crypto/BLAKE2B.ml, src/helpers/map_ext.ml, src/helpers/map_ext.mli
- helpers: expose Map.S_with_yojson
- crypto: make BLAKE2B.Map a Map_with_yojson
We want a BLAKE2B.Map_with_yojson.
Add it to helpers
=> refactor: add map helpers

src/protocol/protocol.ml
We don't handle exceptions in the application of protocol operations. 
Use `try...with`
=> fix: wrap operation application in try/with

src/core_deku/state.ml, src/core_deku/state.mli, src/node/flows.ml, src/smart_contracts/contract_vm.ml, tests/wasm/test_helpers.ml, tests/wasm/test_runtime.ml
We need to know the results of contract origination/calls for indexing.
Add receipts for contract origination/ contract calls
=> add receipts for contract-calls/originations

docs/smart-contracts/wasm_contracts/wasm_mint.wat, src/smart_contracts/contract_vm.ml, src/smart_contracts/conversions.ml, src/smart_contracts/conversions.mli, tests/contracts/helpers_contracts.ml, tests/contracts/test_invocation.ml, tests/contracts/test_origination.ml
Ticket minting lacks proper testing
Add proper tests for minting tickets and improve previous WASM tests
=> Wasm ticket mint testing

scripts/test_tezos_interop.sh, src/tezos_interop/tests/deposit_test.ml, src/tezos_interop/tests/update_state_root_hash_test.ml
=> test/interop: deposit

flake.nix, nix/ligo.nix, nix/shell.nix, src/tezos_interop/consensus.mligo
We want the latest LIGO version
Just download the static binary and put it in the store
=> Install latest ligo via the static binary

src/bin/node/deku_node.ml, src/bin/node/node.ml, src/bin/node/node.mli, src/chain/chain.ml, src/chain/chain.mli, src/consensus/block_pool.ml, src/consensus/block_pool.mli, src/consensus/consensus.ml, src/consensus/judger.ml, src/consensus/timestamp.ml, src/consensus/timestamp.mli, src/constants/deku_constants.ml, src/constants/deku_constants.mli, src/gossip/gossip.ml, src/gossip/gossip.mli
V1 currently leaks memory
This drastically improves it, but doesn't seems to actually solve it. Debugging code was left in place to be removed in the future after fixing everything.
=> v1 better memory

flake.lock, flake.nix, nix/default.nix, nix/overlay.nix, nix/service.nix, src/network/dune, src/network/network.ml
=> Ulrikstrid  v1 alphanet nix

src/bin/node/handlers.ml
This was the only way I could figure out how to make it work. Am just missing something?
=> API: base64 encode ticket data

sdks/typescript-sdk/src/interop.ts, src/chain/chain.ml, src/external_vm/external_vm_client.ml, src/external_vm/external_vm_client.mli, src/external_vm/external_vm_protocol.ml, src/external_vm/external_vm_protocol.mli, src/external_vm/external_vm_server.ml, src/network/network.ml, src/protocol/protocol.ml
noop transaction are sent to the vm
=> v1-vm-noop-transaction

src/bin/node/deku_node.ml, src/chain/chain.ml, src/chain/chain.mli, src/consensus/consensus.ml, src/consensus/consensus.mli, src/consensus/producer.ml, src/consensus/producer.mli, src/indexer/indexer.ml, src/indexer/indexer.mli
chain.json does not contain the last state of the chain
Sqlite has all the blocks, we just need to apply the missing blocks
=> V1 alphanet restart

nix/default.nix, src/bin/node/handlers.ml, src/indexer/dune, src/indexer/indexer.ml, src/indexer/indexer.mli, src/indexer/types.ml
Requests of the indexer were poorly typed
Using ppx rapper
=> Using rapper ppx

deku-p/src/network/network_protocol.ml
First commit allows the chain to make progress again.
With the second commit, I no longer see the error message.
=> fix EADDRINUSE issue

deku-p/src/core/bin/api/api_state.ml, deku-p/src/core/bin/node/deku_node.ml, deku-p/src/core/bin/node/node.ml, deku-p/src/core/chain/chain.ml, deku-p/src/core/chain/dune, deku-p/src/core/consensus/consensus.ml, deku-p/src/core/constants/deku_constants.ml, deku-p/src/core/constants/dune, deku-p/src/core/external_vm/external_process.ml, deku-p/src/core/gossip/gossip.ml, deku-p/src/core/gossip/message_pool.ml, deku-p/src/core/network/network_manager.ml, deku-p/src/core/tezos_interop/js_process.ml, deku-p/src/core/tezos_interop/tezos_bridge.ml
=> fix: replace eprintf with logs

deku-c/wasm-vm/crates/vm_library/benches/util.rs, deku-c/wasm-vm/crates/vm_library/src/run_loop.rs, deku-c/wasm-vm/crates/vm_library/src/state.rs, deku-p/src/core/ledger/address.ml, deku-p/src/core/protocol/protocol.ml
Impossible to apply a vm operation
Fix the serialization and deserializarion thanks to @Zett98
=> fix/wasm-vm: error in serialization/deserialzation

deku-p/src/core/bin/api/deku_api.ml, deku-p/src/core/bin/api/handlers.ml, deku-p/src/core/bin/api/repr.ml, deku-p/src/core/protocol/operation.ml, deku-p/src/core/protocol/operation.mli, deku-p/src/core/tezos_interop/tests/common.ml, deku-p/src/core/tezos_interop/tests/dune, deku-p/src/core/tezos_interop/tests/transaction_test.ml, deku-p/src/core/tezos_interop/tests/withdraw_test.ml, scripts/reset.sh, scripts/start_api.sh, start.sh
- API exposes a binary interface, a json api is more user friendly
- The e2e test was broken too
=> fix/api: json as input

deku-c/deku-c-toolkit/package.json, deku-c/deku-c-toolkit/rollup.config.ts
Installing the library doesn't work
Improve the docker file and the build script
=> config/deku-c-toolkit: build script

deku-p/src/core/bin/api/deku_api.ml, deku-p/src/core/bin/node/deku_node.ml, deku-p/src/core/bin/node/node.ml, deku-p/src/core/block_storage/block_storage.ml, deku-p/src/core/block_storage/block_storage.mli, deku-p/src/core/block_storage/query.ml, deku-p/src/core/block_storage/query.mli, deku-p/src/core/block_storage/types.ml, deku-p/src/core/chain/chain.ml, deku-p/src/core/chain/chain.mli
Our memory requirements keeps growing due to storing blocks in memory.
Here I just use the block storage as a source for any rejoining of the network. Moving the memory problem to disk, data is also compressed on disk, to buy us some time.
=> block_storage: use it for rejoining network

deku-p/src/core/bin/benchmark/deku_benchmark.ml
We want some helper statistics when using deku-benchmark
adds average and per-second statistics to terminal output of the benchmark
=> Add basic statistics for deku benchmarks

scripts/deploy_contracts.sh
Revert change introduced by ba7b6694fe37e2d50101ea0b1fa7bbc11836bae6
=> Fix octez alias

deku-c/client/src/deku-c/contract.ts, deku-c/client/src/deku-c/index.ts, deku-c/client/src/deku-c/utils.ts, deku-c/deku-cli/commands/default-parameters.ts, deku-c/deku-cli/commands/invoke.ts, deku-c/deku-cli/commands/originate-contract.ts, deku-c/deku-cli/core/contract.ts, deku-c/deku-cli/index.ts, docs/Deku-Canonical/deku_c_cli.md
=> Js fix and doc

deku-p/src/core/bin/api/deku_api.ml
Commit cherry-picked from rc-4
The API does not define the on_message callback when listening to the node
Define the callback
=> bug: on_message callback on listen to node function

deku-p/src/core/bin/api/handlers.ml, deku-p/src/core/protocol/operation.ml
Commit cherry-picked from rc-4
No needs to modify the toolkits to have the magic working
=> feat: magic byte
